"""Routing policy — workspace catalog, persona map, and tool whitelist resolution.

The pipeline's "what should I do?" decisions live here:

* ``WORKSPACES`` — the canonical workspace catalog. One entry per
  user-selectable workspace; each entry pins a preferred Ollama model
  (``model_hint``), per-workspace tuning knobs (``predict_limit``,
  ``context_limit``, ``max_concurrent``, ``emits_reasoning``,
  ``system_prompt_append``), and the default tool whitelist
  (``tools``). Loaded at import time from ``config/portal.yaml`` via
  :func:`portal.platform.inference.config.get_workspace_dict`. Keys must match
  ``workspace_routing`` in ``config/backends.yaml`` (generated by
  ``./launch.sh sync-config``; CLAUDE.md §6). Workspaces prefixed
  ``bench-`` are user-pickable but excluded from auto-routing.

* ``_PERSONA_MAP`` — slug → :class:`~portal.platform.inference.config.PersonaSpec`
  for every file under ``config/personas/``. Populated **at import time**
  by ``_load_persona_map()``. The pipeline indexes this by the persona
  slug taken from the chat-completion request.

* ``_resolve_persona_tools`` — combines a persona's optional
  ``tools_allow``/``tools_deny`` with the workspace default to produce
  the effective tool list for one request. Delegates to
  :func:`~portal.platform.inference.config.resolve_preset_tools`.

Import-time side effects:

1. ``_load_persona_map()`` populates ``_PERSONA_MAP`` via
   ``portal.platform.inference.config.load_persona_map()`` — one-time cost at
   pipeline start, fine in production.
2. ``WORKSPACES`` is populated by calling
   :func:`portal.platform.inference.config.load_portal_config`, which validates
   ``config/portal.yaml`` and fails loud on schema errors.

History note: this file is the first extracted sub-module of the
``router_pipe.py`` decomposition (CLAUDE.md alludes to "additional
sub-modules"). The public surface — ``WORKSPACES``, ``_PERSONA_MAP``,
``MAX_TOOL_HOPS``, ``_resolve_persona_tools``, ``_workspace_tools`` —
is re-exported from ``router_pipe.py`` so external callers and tests
see no API change.
"""

from __future__ import annotations

import logging
import os
from typing import Any

from portal.platform.inference.config import (
    PersonaSpec,
    get_workspace_dict,
    load_persona_map,
    load_portal_config,
    resolve_preset_tools,
)

logger = logging.getLogger(__name__)

# ── Persona map (for tool whitelist resolution) ─────────────────────────────
# Loaded at import time via the typed loader in portal.platform.inference.config.
# Keys are persona slugs; values are PersonaSpec instances.
_PERSONA_MAP: dict[str, PersonaSpec] = {}  # type: ignore[assignment]


def _load_persona_map() -> None:
    """Populate ``_PERSONA_MAP`` from the typed PersonaSpec loader.

    Wraps ``portal.platform.inference.config.load_persona_map()`` so the module-level
    dict is populated at import time with the same graceful-empty semantics
    as the legacy loader (missing directory → silent return).
    """
    global _PERSONA_MAP
    _PERSONA_MAP.update(load_persona_map())  # type: ignore[arg-type]


_load_persona_map()

# ─── Canonical workspace catalog ─────────────────────────────────────────────
# Keys here MUST match `workspace_routing` in config/backends.yaml exactly.
# (Consistency check in CLAUDE.md §6 enforces this on startup.)
#
# Per-entry fields (all optional except `name` and `description`):
#   name                       Display name shown in Open WebUI.
#   description                Open WebUI tooltip / model description.
#   model_hint                 Preferred Ollama tag in the routed backend group.
#   tools                      Default tool-name whitelist (overridable per-persona).
#   predict_limit              Max output tokens (Ollama: num_predict).
#   context_limit              Max context window for this workspace.
#   max_concurrent             Per-workspace concurrency cap (router_pipe semaphore).
#   system_prompt_append       String appended after the persona system prompt.
#   think                      False → disable Qwen3/thinking-mode extended thinking
#                              (prevents token-budget exhaustion in <think> blocks).
#   emits_reasoning            True → model emits reasoning chains (DeepSeek-R1 family);
#                              affects how the streaming layer parses delta fields.
#
# Workspace ID prefixes:
#   auto       — auto-routable (the LLM intent classifier may route here).
#   auto-*     — user-selectable AND auto-route targets.
#   bench-*    — user-selectable only; excluded from auto-routing (see
#                router_pipe.py:1046).
# ─────────────────────────────────────────────────────────────────────────────
# Workspace catalog — loaded from config/portal.yaml (M1 migration).
# The data previously lived here as a ~1960-line Python literal. After M1 the
# portal.yaml is the single source of truth; use `./launch.sh sync-config` to
# regenerate all derived artifacts (workspace_routing, .mcp.json, OWUI presets).
# Satisfies CLAUDE.md "Do NOT hardcode model names in Python" (model_hint is
# now in portal.yaml, not in this file).


class _WorkspaceCatalog(dict):
    """dict that hides synthetic ``"<base>::<variant>"`` entries from
    iteration/len/keys/items/values.

    resolve_workspace_variant() (BUILD_PROGRAM_COLLAPSE_V1.md Phase 5/6)
    lazily caches merged variant configs directly into this dict under a
    synthetic key so every existing ``WORKSPACES.get(workspace_id, {})``
    call site picks them up transparently. But code that *iterates* all of
    WORKSPACES (lifespan hint validation, the /metrics workspace count, the
    keyword-classifier id list, Rule 6 cross-checks) must only ever see the
    real portal.yaml catalog — a synthetic entry isn't a real workspace and
    was never meant to be validated/counted/routed-to as one. Direct
    lookup (``.get()``, ``[]``, ``in``) is unaffected — only the
    iteration-shaped views below are filtered.
    """

    def __iter__(self):
        return (k for k in super().__iter__() if "::" not in k)

    def keys(self):  # noqa: D102
        return (k for k in super().keys() if "::" not in k)  # noqa: SIM118

    def items(self):  # noqa: D102
        return ((k, v) for k, v in super().items() if "::" not in k)

    def values(self):  # noqa: D102
        return (v for k, v in self.items())

    def __len__(self):
        return sum(1 for _ in self.__iter__())


WORKSPACES: dict[str, dict[str, Any]] = _WorkspaceCatalog(get_workspace_dict(load_portal_config()))

# ── Tool-call helpers (M2) ──────────────────────────────────────────────────

# Max iterations of the streaming tool-call loop before the pipeline gives up
# and returns whatever the model has so far. Env-overridable. Consumed in
# router_pipe._stream_with_tool_loop_impl.
MAX_TOOL_HOPS = int(os.environ.get("MAX_TOOL_HOPS", "20"))


def _workspace_tools(workspace_id: str) -> list[str]:
    """Return the default tool whitelist for ``workspace_id``.

    The unknown-workspace path returns ``[]`` rather than raising, so a
    request referencing a since-removed workspace still serves — just
    without any tools advertised to the model.

    Used directly by ``router_pipe.py`` (re-exported there for tests
    and external callers; see the ``noqa: F401`` at line 529) and
    indirectly via ``_resolve_persona_tools``.

    Args:
        workspace_id: A ``WORKSPACES`` key. Unknown ids return ``[]``.

    Returns:
        Tool names from the workspace's ``tools`` field, or ``[]``.
    """
    return WORKSPACES.get(workspace_id, {}).get("tools", [])


def _resolve_persona_tools(persona: PersonaSpec | dict, workspace_id: str) -> list[str]:
    """Resolve the effective tool list for one persona × workspace pair.

    Delegates to ``portal.platform.inference.config.resolve_preset_tools`` — the single
    tool-resolution path. Accepts both ``PersonaSpec`` (typed path) and legacy
    ``dict`` (used by callers that still hold raw YAML) for backward compat.

    Resolution:
    1. ``tools_allow`` absent (``None``) → use workspace default unchanged.
    2. ``tools_allow`` present (even ``[]``) → replaces workspace default.
    3. ``tools_deny`` removes any matching entries.

    Returns sorted, deduplicated tool names.
    """
    ws_tools = _workspace_tools(workspace_id)
    if isinstance(persona, PersonaSpec):
        return resolve_preset_tools(persona, ws_tools)
    # Legacy dict path (still used by router_pipe direct dict lookups)
    raw_allow = persona.get("tools_allow")
    deny = set(persona.get("tools_deny", []) or [])
    effective = set(ws_tools) if raw_allow is None else set(raw_allow)
    return sorted(effective - deny)
