// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

intersection() { cube([40, 30, 10]); hull() { translate([1.5, 1.5, 0]) linear_extrude(height=0.01) offset(r=0) square([37, 27]); translate([0, 0, 1.5]) linear_extrude(height=0.01) offset(r=0) square([40, 30]); translate([0, 0, 10]) linear_extrude(height=0.01) offset(r=0) square([40, 30]); } }
