// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

intersection() { translate([15, 15, 0]) cylinder(h=12, r=15, $fn=$fn); hull() { translate([15,15,0]) cylinder(h=0.01,r=15,$fn=$fn); translate([15,15,10.5]) cylinder(h=0.01,r=13.5,$fn=$fn); } }
