// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

intersection() { intersection() { cube([35, 25, 8]); hull() { translate([0, 0, 0]) linear_extrude(height=0.01) offset(r=0) square([35, 25]); translate([1, 1, 8]) linear_extrude(height=0.01) offset(r=0) square([33, 23]); translate([0, 0, 7]) linear_extrude(height=0.01) offset(r=0) square([35, 25]); } } hull() { translate([0.5, 0.5, 0]) linear_extrude(height=0.01) offset(r=0) square([34, 24]); translate([0, 0, 0.5]) linear_extrude(height=0.01) offset(r=0) square([35, 25]); translate([0, 0, 8]) linear_extrude(height=0.01) offset(r=0) square([35, 25]); } }
