// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { cube([60, 60, 5]); translate([45, 30, 5.5]) rotate([180, 0, 0]) cylinder(h=6, r=2, $fn=$fn); translate([37.5, 42.9904, 5.5]) rotate([180, 0, 0]) cylinder(h=6, r=2, $fn=$fn); translate([22.5, 42.9904, 5.5]) rotate([180, 0, 0]) cylinder(h=6, r=2, $fn=$fn); translate([15, 30, 5.5]) rotate([180, 0, 0]) cylinder(h=6, r=2, $fn=$fn); translate([22.5, 17.0096, 5.5]) rotate([180, 0, 0]) cylinder(h=6, r=2, $fn=$fn); translate([37.5, 17.0096, 5.5]) rotate([180, 0, 0]) cylinder(h=6, r=2, $fn=$fn); }
