// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { translate([15, 15, 0]) cylinder(h=12, r=15, $fn=$fn); union() { translate([15, 15, 12.5]) rotate([180, 0, 0]) cylinder(h=13, r=4, $fn=$fn); translate([15, 15, 12.5]) rotate([180, 0, 0]) cylinder(h=3.5, r=6, $fn=$fn); } }
