// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

union() { cube([50, 40, 4]); difference() { translate([8, 8, 3.5]) rotate([0, 0, 0]) cylinder(h=8.5, r=4, $fn=$fn); translate([8, 8, 3.5]) rotate([0, 0, 0]) cylinder(h=9, r=1.5, $fn=$fn); } }
