// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { cube([40, 30, 10]); translate([10, 6, 10.5]) rotate([180, 0, 0]) cylinder(h=11, r=2, $fn=$fn); }
union() { translate([5, 5, 10]) sphere(r=3, $fn=$fn); rotate([0, 90, 0]) scale([1, 2, 1]) cylinder(h=6, r=2, $fn=$fn); };
