// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

intersection() { cube([40, 30, 10]); hull() { translate([3, 3, 0]) linear_extrude(height=0.01) offset(r=1.5) square([34, 24]); translate([2.5365, 2.5365, 0.3]) linear_extrude(height=0.01) offset(r=1.5) square([34.9271, 24.9271]); translate([2.1183, 2.1183, 0.6]) linear_extrude(height=0.01) offset(r=1.5) square([35.7634, 25.7634]); translate([1.7865, 1.7865, 0.9]) linear_extrude(height=0.01) offset(r=1.5) square([36.4271, 26.4271]); translate([1.5734, 1.5734, 1.2]) linear_extrude(height=0.01) offset(r=1.5) square([36.8532, 26.8532]); translate([1.5, 1.5, 1.5]) linear_extrude(height=0.01) offset(r=1.5) square([37, 27]); translate([1.5, 1.5, 10]) linear_extrude(height=0.01) offset(r=1.5) square([37, 27]); } }
