// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { translate([18, 18, 0]) cylinder(h=6, r=18, $fn=$fn); translate([28, 18, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); translate([25.0711, 25.0711, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); translate([18, 28, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); translate([10.9289, 25.0711, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); translate([8, 18, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); translate([10.9289, 10.9289, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); translate([18, 8, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); translate([25.0711, 10.9289, 6.5]) rotate([180, 0, 0]) cylinder(h=7, r=1.5, $fn=$fn); }
