// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { cube([80, 30, 4]); union() { translate([15, 15, 4.5]) rotate([180, 0, 0]) cylinder(h=5, r=5, $fn=$fn); translate([15, 15, 4.5]) rotate([180, 0, 0]) cylinder(h=1.5, r1=6, r2=5, $fn=$fn); } union() { translate([40, 15, 4.5]) rotate([180, 0, 0]) cylinder(h=5, r=5, $fn=$fn); translate([40, 15, 4.5]) rotate([180, 0, 0]) cylinder(h=1.5, r1=6, r2=5, $fn=$fn); } union() { translate([65, 15, 4.5]) rotate([180, 0, 0]) cylinder(h=5, r=5, $fn=$fn); translate([65, 15, 4.5]) rotate([180, 0, 0]) cylinder(h=1.5, r1=6, r2=5, $fn=$fn); } }
