// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { cube([40, 30, 10]); union() { translate([10, 6, 10.5]) rotate([180, 0, 0]) cylinder(h=11, r=2, $fn=$fn); translate([10, 6, 10.5]) rotate([180, 0, 0]) cylinder(h=1, r1=2.5, r2=2, $fn=$fn); translate([10, 6, 10.5]) rotate([180, 0, 0]) cylinder(h=2.5, r=4, $fn=$fn); translate([10, 6, 10.5]) rotate([180, 0, 0]) cylinder(h=3.3759, r1=4.5, r2=2, $fn=$fn); } }
