// units=mm — generated by scad_emitter.py
// part=param part
$fn = 48;

w = 50;
d = 30;
t = 4;
hole_d = 5;

difference() { cube([50, 30, 4]); translate([25, 15, 4.5]) rotate([180, 0, 0]) cylinder(h=5, r=2.5, $fn=$fn); }
