// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { translate([15, 15, 0]) cylinder(h=12, r=15, $fn=$fn); translate([15, 15, 2]) cylinder(h=8, r=13, $fn=$fn); translate([2, -0.5, 2]) cube([26, 15.5, 8]); }
