// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { translate([15, 15, 0]) cylinder(h=12, r=15, $fn=$fn); translate([15, 15, -0.5]) cylinder(h=10.5, r=13, $fn=$fn); }
