// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

union() { cube([50, 40, 3]); difference() { translate([7, 7, 2.5]) rotate([0, 0, 0]) cylinder(h=6.5, r=3, $fn=$fn); translate([7, 7, 2.5]) rotate([0, 0, 0]) cylinder(h=7, r=1.25, $fn=$fn); } difference() { translate([7, 33, 2.5]) rotate([0, 0, 0]) cylinder(h=6.5, r=3, $fn=$fn); translate([7, 33, 2.5]) rotate([0, 0, 0]) cylinder(h=7, r=1.25, $fn=$fn); } difference() { translate([43, 7, 2.5]) rotate([0, 0, 0]) cylinder(h=6.5, r=3, $fn=$fn); translate([43, 7, 2.5]) rotate([0, 0, 0]) cylinder(h=7, r=1.25, $fn=$fn); } difference() { translate([43, 33, 2.5]) rotate([0, 0, 0]) cylinder(h=6.5, r=3, $fn=$fn); translate([43, 33, 2.5]) rotate([0, 0, 0]) cylinder(h=7, r=1.25, $fn=$fn); } }
