// units=mm — generated by scad_emitter.py
// part=unnamed
$fn = 48;

difference() { cube([50, 30, 3]); translate([8, 5, -0.5]) cube([3, 20, 4]); translate([16, 5, -0.5]) cube([3, 20, 4]); translate([24, 5, -0.5]) cube([3, 20, 4]); translate([32, 5, -0.5]) cube([3, 20, 4]); translate([40, 5, -0.5]) cube([3, 20, 4]); }
