"""HuggingChat (chat-ui) adapter — generates models.yaml config file."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml as _yaml

from frontend_seeder.source import (
    PORTAL_ROOT,
    load_workspaces,
    production_workspaces,
)

PIPELINE_API_KEY = os.environ.get("PIPELINE_API_KEY", "")
PIPELINE_URL = os.environ.get("PIPELINE_URL", "http://portal-pipeline:9099/v1")


def generate_models_yaml(output_path: Path | None = None) -> str:
    """Generate chat-ui models.yaml with all Portal 5 workspaces."""
    workspaces = production_workspaces(load_workspaces())

    models: list[dict[str, Any]] = []
    for ws_id, ws_cfg in workspaces.items():
        entry: dict[str, Any] = {
            "name": ws_cfg["name"],
            "displayName": ws_cfg["name"],
            "description": ws_cfg.get("description", ""),
            "endpoints": [
                {
                    "type": "openai",
                    "url": PIPELINE_URL,
                    "authorization": f"Bearer {PIPELINE_API_KEY}",
                    "apiKey": PIPELINE_API_KEY,
                    "model": ws_id,
                }
            ],
            "parameters": {
                "temperature": 0.7,
                "max_new_tokens": 4096,
            },
        }
        desc = ws_cfg.get("description", "")
        if desc:
            entry["parameters"]["system_prompt"] = desc
        models.append(entry)

    out = _yaml.dump(models, default_flow_style=False, allow_unicode=True, sort_keys=False)
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(out)
        print(f"  [huggingchat] Wrote {output_path} ({len(models)} models)")
    return out


def generate_dotenv(output_path: Path | None = None) -> str:
    """Generate .env for chat-ui (HuggingFace)."""
    lines = [
        "# Auto-generated by Portal 5 frontend_seeder — do not hand-edit",
        f'MODELS=`{generate_models_yaml()}`',
        "ALLOW_INSECURE_COOKIES=true",
        "HF_ACCESS_TOKEN=local",
        "PUBLIC_APP_NAME=Portal 5",
        "PUBLIC_APP_DESCRIPTION=Local AI platform powered by Portal 5",
        "PUBLIC_ORIGIN=http://localhost:8084",
    ]
    content = "\n".join(lines) + "\n"
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
        print(f"  [huggingchat] Wrote {output_path}")
    return content
