"""Prometheus metrics: the single CollectorRegistry and all Portal 5 collectors.

Owns ``_REGISTRY`` and every Counter/Gauge/Histogram. Imported by router_pipe
(facade), state, power, tools, and routing. MUST be import-once safe: with
multiple uvicorn workers each process imports this module exactly once, so
collectors are declared exactly once here and nowhere else.

``PROMETHEUS_MULTIPROC_DIR`` is set in ``portal_pipeline.__main__`` before this
module is first imported — do not set it here.
"""

from __future__ import annotations

import logging

from prometheus_client import CollectorRegistry, Counter, Gauge, Histogram

logger = logging.getLogger(__name__)

# ── Prometheus metrics (per-model granularity) ────────────────────────────
# Use a separate registry to avoid conflicts with default prometheus_client
# global state when running with multiple uvicorn workers.
_REGISTRY = CollectorRegistry(auto_describe=True)

_tokens_per_second = Histogram(
    "portal_tokens_per_second",
    "Tokens generated per second by model and workspace",
    ["model", "workspace"],
    buckets=[5, 10, 20, 30, 40, 50, 60, 80, 100, 150, 200],
    registry=_REGISTRY,
)

_output_tokens = Counter(
    "portal_output_tokens_total",
    "Total output tokens generated by model and workspace",
    ["model", "workspace"],
    registry=_REGISTRY,
)

_input_tokens = Counter(
    "portal_input_tokens_total",
    "Total input tokens processed by model and workspace",
    ["model", "workspace"],
    registry=_REGISTRY,
)

_requests_by_model = Counter(
    "portal_requests_by_model_total",
    "Total requests routed to each model",
    ["model", "workspace"],
    registry=_REGISTRY,
)

_response_time_seconds = Histogram(
    "portal_response_time_seconds",
    "End-to-end response time (request received to last byte) per model and workspace",
    ["model", "workspace"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0],
    registry=_REGISTRY,
)

_requests_total = Counter(
    "portal_requests_total",
    "Total requests by workspace (aggregated across workers)",
    ["workspace"],
    registry=_REGISTRY,
)

_errors_total = Counter(
    "portal_errors_total",
    "Total failed requests by workspace and error type",
    ["workspace", "error_type"],
    registry=_REGISTRY,
)

_concurrent_requests = Gauge(
    "portal_concurrent_requests",
    "Number of requests currently being processed",
    registry=_REGISTRY,
)

_persona_usage = Counter(
    "persona_usage_total",
    "Total requests by persona/model preset as selected by user",
    ["persona", "model"],
    registry=_REGISTRY,
)

# ── Tool-call metrics (M2) ─────────────────────────────────────────────────
_tool_calls_total = Counter(
    "portal5_tool_calls_total",
    "Total tool calls dispatched, by tool name and workspace",
    ["tool", "workspace"],
    registry=_REGISTRY,
)
_tool_call_duration = Histogram(
    "portal5_tool_call_duration_seconds",
    "Tool call dispatch latency in seconds, by tool name",
    ["tool"],
    buckets=[0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60],
    registry=_REGISTRY,
)
_tool_call_errors = Counter(
    "portal5_tool_call_errors_total",
    "Tool calls that returned error, by tool and workspace",
    ["tool", "workspace"],
    registry=_REGISTRY,
)
_tool_workspace_strip = Counter(
    "portal5_tool_workspace_strip_total",
    "Tools stripped from request because workspace doesn't authorize them",
    ["workspace"],
    registry=_REGISTRY,
)
_tool_loop_hops = Histogram(
    "portal5_tool_loop_hops",
    "Number of hops in the multi-turn tool loop per request",
    ["workspace"],
    buckets=[1, 2, 3, 5, 8, 10, 15, 20],
    registry=_REGISTRY,
)

# ── Power & cost metrics (M6-T02) ─────────────────────────────────────────
_power_current_watts = Gauge(
    "portal5_power_current_watts",
    "Current total power draw across CPU+GPU+ANE+DRAM",
    registry=_REGISTRY,
)
_power_cpu_watts = Gauge("portal5_power_cpu_watts", "CPU package power", registry=_REGISTRY)
_power_gpu_watts = Gauge("portal5_power_gpu_watts", "GPU power", registry=_REGISTRY)
_power_ane_watts = Gauge("portal5_power_ane_watts", "ANE power", registry=_REGISTRY)
_power_dram_watts = Gauge("portal5_power_dram_watts", "DRAM power", registry=_REGISTRY)
_power_avg_1min_watts = Gauge(
    "portal5_power_avg_1min_watts", "1-minute average power", registry=_REGISTRY
)
_energy_consumed_ws_total = Counter(
    "portal5_energy_consumed_watt_seconds_total",
    "Cumulative energy consumed by the host",
    registry=_REGISTRY,
)
_energy_by_workspace_ws = Counter(
    "portal5_energy_by_workspace_watt_seconds_total",
    "Estimated energy attributed to a workspace",
    ["workspace"],
    registry=_REGISTRY,
)
_request_energy_ws = Histogram(
    "portal5_request_energy_watt_seconds",
    "Estimated energy per request (avg_power * duration)",
    ["workspace", "persona"],
    buckets=[1, 5, 10, 30, 60, 120, 300, 600, 1800, 3600],
    registry=_REGISTRY,
)

# ── Rate-limit metrics (M6-T05) ───────────────────────────────────────────
_workspace_semaphore_busy_total_metric = Counter(
    "portal5_workspace_semaphore_busy_total",
    "Requests rejected because workspace concurrency limit reached",
    ["workspace"],
    registry=_REGISTRY,
)
_workspace_semaphore_busy_total = _workspace_semaphore_busy_total_metric

# Accumulator for daily summary (updated by _record_response_time, reset by _save_state)
_total_response_time_ms: float = 0.0


def _record_response_time(model: str, workspace: str, duration_seconds: float) -> None:
    """Record end-to-end response time for one request.

    Updates the Prometheus histogram ``_response_time_seconds``
    (per-model/workspace buckets for Grafana) and the module-level
    aggregate ``_total_response_time_ms``. The aggregate is divided
    by the request count in the daily summary to produce average
    response time.

    Failure handling: bare except → ``logger.debug``. A metric
    failure must not break the request path.

    Args:
        model: Concrete model id.
        workspace: Workspace id from the request.
        duration_seconds: End-to-end time from request received to
            last byte sent.
    """
    try:
        _response_time_seconds.labels(model=model, workspace=workspace).observe(duration_seconds)
        global _total_response_time_ms
        _total_response_time_ms += duration_seconds * 1000
    except Exception as e:
        logger.debug("Failed to record response time: %s", e)
