"""Routing policy — workspace catalog, persona map, and tool whitelist resolution.

The pipeline's "what should I do?" decisions live here:

* ``WORKSPACES`` — the canonical workspace catalog. One entry per
  user-selectable workspace; each entry pins a preferred Ollama model
  (``model_hint``), per-workspace tuning knobs (``predict_limit``,
  ``context_limit``, ``max_concurrent``, ``emits_reasoning``,
  ``system_prompt_append``), and the default tool whitelist
  (``tools``). Loaded at import time from ``config/portal.yaml`` via
  :func:`portal_pipeline.config.get_workspace_dict`. Keys must match
  ``workspace_routing`` in ``config/backends.yaml`` (generated by
  ``./launch.sh sync-config``; CLAUDE.md §6). Workspaces prefixed
  ``bench-`` are user-pickable but excluded from auto-routing.

* ``_PERSONA_MAP`` — slug → persona YAML dict for every file under
  ``config/personas/``. Populated **at import time** by
  ``_load_persona_map()``. The pipeline indexes this by the persona
  slug taken from the chat-completion request.

* ``_resolve_persona_tools`` — combines a persona's optional
  ``tools_allow``/``tools_deny`` with the workspace default to produce
  the effective tool list for one request. This is the policy gate
  before ``tool_registry.get_openai_tools`` is asked to advertise
  anything to the model.

* ``_resolve_persona_browser_policy`` — defined but **currently has no
  callers in the active codebase**. Documented here for completeness;
  see its own docstring for the intended consumer.

Import-time side effects:

1. ``_load_persona_map()`` reads every ``*.yaml`` under
   ``<repo>/config/personas/`` — one-time cost, fine in production.
2. ``WORKSPACES`` is populated by calling
   :func:`portal_pipeline.config.load_portal_config`, which validates
   ``config/portal.yaml`` and fails loud on schema errors.

History note: this file is the first extracted sub-module of the
``router_pipe.py`` decomposition (CLAUDE.md alludes to "additional
sub-modules"). The public surface — ``WORKSPACES``, ``_PERSONA_MAP``,
``MAX_TOOL_HOPS``, ``_resolve_persona_tools``, ``_workspace_tools`` —
is re-exported from ``router_pipe.py`` so external callers and tests
see no API change.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

from portal_pipeline.config import get_workspace_dict, load_portal_config

logger = logging.getLogger(__name__)

# ── Persona map (for tool whitelist resolution) ─────────────────────────────
_PERSONA_MAP: dict[str, dict[str, Any]] = {}


def _load_persona_map() -> None:
    """Populate ``_PERSONA_MAP`` from every ``*.yaml`` under ``config/personas/``.

    Called exactly once, at module import time (line 40). The pipeline
    has no hot-reload path for personas — operator workflow is to edit
    YAML and restart the pipeline container.

    Each file is keyed in ``_PERSONA_MAP`` by its ``slug:`` field if
    present, otherwise by the filename stem. The fallback exists so a
    persona YAML missing a ``slug:`` line still loads instead of
    failing silently.

    Failure modes — all logged, never raised:

    * ``config/personas/`` directory missing → silent return; the
      registry stays empty.
    * Top-level YAML error → logged warning; no personas load.
    * One file invalid → debug log for that file; surrounding files
      still load.

    The pipeline must reach a serving state even with a broken
    persona catalog so operators can fix YAML without a manual
    process bounce. Same "graceful empty" pattern as
    ``cluster_backends._load_config``.
    """
    global _PERSONA_MAP
    personas_dir = Path(__file__).resolve().parent.parent.parent / "config" / "personas"
    if not personas_dir.is_dir():
        return
    try:
        import yaml  # noqa: F811 — pyyaml is a pipeline dependency

        for yf in sorted(personas_dir.glob("*.yaml")):
            try:
                data = yaml.safe_load(yf.read_text()) or {}
                slug = data.get("slug", yf.stem)
                _PERSONA_MAP[slug] = data
            except Exception as e:
                logger.debug("Failed to load persona %s: %s", yf, e)
    except Exception as e:
        logger.warning("Failed to load persona map: %s", e)


_load_persona_map()

# ─── Canonical workspace catalog ─────────────────────────────────────────────
# Keys here MUST match `workspace_routing` in config/backends.yaml exactly.
# (Consistency check in CLAUDE.md §6 enforces this on startup.)
#
# Per-entry fields (all optional except `name` and `description`):
#   name                       Display name shown in Open WebUI.
#   description                Open WebUI tooltip / model description.
#   model_hint                 Preferred Ollama tag in the routed backend group.
#   tools                      Default tool-name whitelist (overridable per-persona).
#   predict_limit              Max output tokens (Ollama: num_predict).
#   context_limit              Max context window for this workspace.
#   max_concurrent             Per-workspace concurrency cap (router_pipe semaphore).
#   system_prompt_append       String appended after the persona system prompt.
#   think                      False → disable Qwen3/thinking-mode extended thinking
#                              (prevents token-budget exhaustion in <think> blocks).
#   emits_reasoning            True → model emits reasoning chains (DeepSeek-R1 family);
#                              affects how the streaming layer parses delta fields.
#
# Workspace ID prefixes:
#   auto       — auto-routable (the LLM intent classifier may route here).
#   auto-*     — user-selectable AND auto-route targets.
#   bench-*    — user-selectable only; excluded from auto-routing (see
#                router_pipe.py:1046).
# ─────────────────────────────────────────────────────────────────────────────
# Workspace catalog — loaded from config/portal.yaml (M1 migration).
# The data previously lived here as a ~1960-line Python literal. After M1 the
# portal.yaml is the single source of truth; use `./launch.sh sync-config` to
# regenerate all derived artifacts (workspace_routing, .mcp.json, OWUI presets).
# Satisfies CLAUDE.md "Do NOT hardcode model names in Python" (model_hint is
# now in portal.yaml, not in this file).
WORKSPACES: dict[str, dict[str, Any]] = get_workspace_dict(load_portal_config())

# ── Tool-call helpers (M2) ──────────────────────────────────────────────────

# Max iterations of the streaming tool-call loop before the pipeline gives up
# and returns whatever the model has so far. Env-overridable. Consumed in
# router_pipe._stream_with_tool_loop_impl.
MAX_TOOL_HOPS = int(os.environ.get("MAX_TOOL_HOPS", "20"))


def _workspace_tools(workspace_id: str) -> list[str]:
    """Return the default tool whitelist for ``workspace_id``.

    The unknown-workspace path returns ``[]`` rather than raising, so a
    request referencing a since-removed workspace still serves — just
    without any tools advertised to the model.

    Used directly by ``router_pipe.py`` (re-exported there for tests
    and external callers; see the ``noqa: F401`` at line 529) and
    indirectly via ``_resolve_persona_tools``.

    Args:
        workspace_id: A ``WORKSPACES`` key. Unknown ids return ``[]``.

    Returns:
        Tool names from the workspace's ``tools`` field, or ``[]``.
    """
    return WORKSPACES.get(workspace_id, {}).get("tools", [])


def _resolve_persona_tools(persona: dict, workspace_id: str) -> list[str]:
    """Resolve the effective tool list for one persona × workspace pair.

    This is the **least-privilege policy gate** for tool calling. The
    workspace declares a default "what tools are reasonable here"; the
    persona refines it per the YAML's ``tools_allow``/``tools_deny``
    fields. Resolution rules:

    1. ``tools_allow`` **absent** from the persona dict (or ``None``)
       → use the workspace default tools unchanged.
    2. ``tools_allow`` **present with an explicit list** (even ``[]``)
       → that exact set **replaces** the workspace default.
       ``tools_allow: []`` means *no tools at all*.
    3. ``tools_deny`` then strips anything from the result.

    Args:
        persona: The persona YAML dict from ``_PERSONA_MAP``. An empty
            dict (the standard fallback for unknown personas) yields
            the workspace default unchanged because ``get("tools_allow", None)``
            returns ``None``.
        workspace_id: Workspace key for the default fallback; unknown
            ids contribute ``[]`` as the base.

    Returns:
        Sorted, deduplicated tool names. Sorted alphabetically for
        determinism in caching, tests, and logs; downstream
        ``tool_registry.get_openai_tools`` preserves whatever order it
        receives.
    """
    raw_allow = persona.get("tools_allow")
    persona_deny = set(persona.get("tools_deny", []) or [])
    effective = set(_workspace_tools(workspace_id)) if raw_allow is None else set(raw_allow)
    return sorted(effective - persona_deny)


def _resolve_persona_browser_policy(persona: dict) -> dict:
    """Return the persona's browser policy dict with defaults applied.

    **Currently has no callers in the active codebase.** The intended
    consumer is the Playwright-backed browser MCP at port 8923, which
    expects allowlist / blocklist / profile / credential-fill policy
    on a per-persona basis (see ``portal_mcp/browser/browser_mcp.py``
    for the corresponding enforcement side). The wiring that would
    pass this through the pipeline to that MCP is not present at
    HEAD. Persona YAMLs do declare ``browser_policy:`` blocks, so the
    persona-side data shape is in place; only the request-time
    plumbing is missing.

    Treat as documentation of the intended shape until the wiring
    lands. Do not delete: removing it would also remove the canonical
    record of what fields a persona's ``browser_policy`` may declare.

    Field defaults applied for missing keys:

    * ``allowed_domains``                — ``[]`` (open by default;
      browser MCP's own ``PLAYWRIGHT_MCP_BLOCKED_ORIGINS`` env still
      applies).
    * ``blocked_domains``                — ``[]``.
    * ``default_profile``                — ``"_isolated"``
      (ephemeral, cookies discarded).
    * ``force_credential_fill``          — ``False``.
    * ``max_navigations_per_session``    — ``50``.

    Args:
        persona: Persona YAML dict; ``persona.browser_policy`` (if
            present) is consulted, otherwise defaults are returned.

    Returns:
        A fully-populated policy dict with the five fields above.
    """
    bp = persona.get("browser_policy", {}) or {}
    return {
        "allowed_domains": bp.get("allowed_domains") or [],
        "blocked_domains": bp.get("blocked_domains") or [],
        "default_profile": bp.get("default_profile", "_isolated"),
        "force_credential_fill": bp.get("force_credential_fill", False),
        "max_navigations_per_session": bp.get("max_navigations_per_session", 50),
    }
