"""Portal 5.2.1 — Intelligent Router Pipeline.

Exposes OpenAI-compatible /v1/models and /v1/chat/completions.
Open WebUI connects here as its sole model source.
Routes by workspace to the appropriate backend + model.
"""

from __future__ import annotations

import asyncio
import hmac
import importlib.metadata
import json
import logging
import os
import re
import time
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from portal_pipeline.notifications import NotificationDispatcher, NotificationScheduler

import httpx
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse, PlainTextResponse, StreamingResponse
from prometheus_client import CollectorRegistry, Counter, Histogram, generate_latest

from portal_pipeline.cluster_backends import BackendRegistry

logger = logging.getLogger(__name__)

# Basic Prometheus-compatible metrics counter
_request_count: dict[str, int] = {}
_startup_time = time.time()

# Maximum request body size (default 4MB)
_MAX_REQUEST_BYTES: int = int(os.environ.get("MAX_REQUEST_BYTES", str(4 * 1024 * 1024)))

# Extended stats tracked for daily summary (aggregated from Prometheus metrics)
# These are updated on every request and read by the notification scheduler.
_total_response_time_ms: float = 0.0
_total_tps: float = 0.0
_request_tps_count: int = 0
_total_input_tokens: int = 0
_total_output_tokens: int = 0
_req_count_by_model: dict[str, int] = {}  # model_name -> count (plain dict for summary)

# Notification subsystem handles operational alerts and daily summaries
_notification_dispatcher: NotificationDispatcher | None = None
_notification_scheduler: NotificationScheduler | None = None

# Cached multiprocess collector registry — rebuilt only when the process
# directory changes, not on every /metrics scrape.
_mp_registry_cache: CollectorRegistry | None = None
_mp_registry_dir_cache: str | None = None

# ── Prometheus metrics (per-model granularity) ────────────────────────────
# Use a separate registry to avoid conflicts with default prometheus_client
# global state when running with multiple uvicorn workers.
_REGISTRY = CollectorRegistry(auto_describe=True)

_tokens_per_second = Histogram(
    "portal_tokens_per_second",
    "Tokens generated per second by model and workspace",
    ["model", "workspace"],
    buckets=[5, 10, 20, 30, 40, 50, 60, 80, 100, 150, 200],
    registry=_REGISTRY,
)

_output_tokens = Counter(
    "portal_output_tokens_total",
    "Total output tokens generated by model and workspace",
    ["model", "workspace"],
    registry=_REGISTRY,
)

_input_tokens = Counter(
    "portal_input_tokens_total",
    "Total input tokens processed by model and workspace",
    ["model", "workspace"],
    registry=_REGISTRY,
)

_requests_by_model = Counter(
    "portal_requests_by_model_total",
    "Total requests routed to each model",
    ["model", "workspace"],
    registry=_REGISTRY,
)

_response_time_seconds = Histogram(
    "portal_response_time_seconds",
    "End-to-end response time (request received to last byte) per model and workspace",
    ["model", "workspace"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0],
    registry=_REGISTRY,
)


def _record_usage(
    model: str, workspace: str, data: dict, elapsed_seconds: float | None = None
) -> None:
    """Extract usage fields from an Ollama or OpenAI-format response dict and record metrics.

    Safe to call with incomplete dicts — missing fields are skipped.
    Supports both Ollama native format (eval_count, eval_duration, prompt_eval_count)
    and OpenAI compatibility format (completion_tokens, prompt_tokens).
    TPS computation (fastest available method):
      1. eval_duration_ns  — Ollama native model compute time (preferred)
      2. elapsed_seconds    — wall-clock time from stream start (streaming fallback)
    Updates both Prometheus histograms/counters and module-level aggregates
    used by the daily summary scheduler.
    """
    try:
        global \
            _total_output_tokens, \
            _total_input_tokens, \
            _total_tps, \
            _request_tps_count, \
            _req_count_by_model
        # Prefer OpenAI format fields (completion_tokens / prompt_tokens)
        # Fall back to Ollama native (eval_count / prompt_eval_count)
        completion_tokens = int(data.get("completion_tokens") or data.get("eval_count") or 0)
        prompt_tokens = int(data.get("prompt_tokens") or data.get("prompt_eval_count") or 0)
        eval_duration_ns = int(data.get("eval_duration") or 0)

        _requests_by_model.labels(model=model, workspace=workspace).inc()

        if completion_tokens > 0:
            _output_tokens.labels(model=model, workspace=workspace).inc(completion_tokens)
            _total_output_tokens += completion_tokens

        if prompt_tokens > 0:
            _input_tokens.labels(model=model, workspace=workspace).inc(prompt_tokens)
            _total_input_tokens += prompt_tokens

        # TPS: prefer Ollama's eval_duration; fall back to wall-clock elapsed time (streaming)
        if completion_tokens > 0 and eval_duration_ns > 0:
            tps = completion_tokens / (eval_duration_ns / 1_000_000_000)
            _tokens_per_second.labels(model=model, workspace=workspace).observe(tps)
            # Update running totals for daily summary
            _total_tps += tps
            _request_tps_count += 1
            logger.debug(
                "Usage: workspace=%s model=%s tokens=%d tps=%.1f (model time)",
                workspace,
                model,
                completion_tokens,
                tps,
            )
        elif completion_tokens > 0 and elapsed_seconds and elapsed_seconds > 0:
            tps = completion_tokens / elapsed_seconds
            _tokens_per_second.labels(model=model, workspace=workspace).observe(tps)
            # Update running totals for daily summary
            _total_tps += tps
            _request_tps_count += 1
            logger.debug(
                "Usage: workspace=%s model=%s tokens=%d tps=%.1f (wall clock)",
                workspace,
                model,
                completion_tokens,
                tps,
            )

        # Track per-model request count for summary (plain dict, not the Counter)
        _req_count_by_model[model] = _req_count_by_model.get(model, 0) + 1

    except Exception as e:
        logger.debug("Failed to record usage metrics: %s", e)


def _record_response_time(model: str, workspace: str, duration_seconds: float) -> None:
    """Record end-to-end response time for a request.

    Updates both Prometheus histogram and module-level aggregate for the daily summary.
    """
    try:
        _response_time_seconds.labels(model=model, workspace=workspace).observe(duration_seconds)
        global _total_response_time_ms
        _total_response_time_ms += duration_seconds * 1000
    except Exception as e:
        logger.debug("Failed to record response time: %s", e)


# Canonical workspace definitions — must match backends.yaml workspace_routing keys
# model_hint: preferred Ollama model tag within the routed backend group
WORKSPACES: dict[str, dict[str, str]] = {
    "auto": {
        "name": "🤖 Portal Auto Router",
        "description": (
            "Intelligently routes to the best specialist model based on your question. "
            "Security/redteam topics → BaronLLM. Coding → Qwen3-Coder. "
            "Reasoning/research → DeepSeek-R1. Other → general."
        ),
        "model_hint": "dolphin-llama3:8b",
    },
    "auto-coding": {
        "name": "💻 Portal Code Expert",
        "description": "Code generation, debugging, architecture review",
        "model_hint": "mlx-community/Qwen3-Coder-Next-4bit",
    },
    "auto-security": {
        "name": "🔒 Portal Security Analyst",
        "description": "Security analysis, hardening, vulnerability assessment",
        "model_hint": "baronllm:q6_k",
    },
    "auto-redteam": {
        "name": "🔴 Portal Red Team",
        "description": "Offensive security, penetration testing, exploit research",
        "model_hint": "baronllm:q6_k",
    },
    "auto-blueteam": {
        "name": "🔵 Portal Blue Team",
        "description": "Defensive security, incident response, threat hunting",
        "model_hint": "lily-cybersecurity:7b-q4_k_m",
    },
    "auto-creative": {
        "name": "✍️  Portal Creative Writer",
        "description": "Creative writing, storytelling, content generation",
        "model_hint": "dolphin-llama3:8b",
    },
    "auto-reasoning": {
        "name": "🧠 Portal Deep Reasoner",
        "description": "Complex analysis, research synthesis, step-by-step reasoning",
        "model_hint": "deepseek-r1:32b-q4_k_m",
    },
    "auto-documents": {
        "name": "📄 Portal Document Builder",
        "description": "Create Word, Excel, PowerPoint via MCP tools",
        "model_hint": "qwen3.5:9b",  # MiniMax-M2.1 removed (138 GB, won't fit in 48 GB)
    },
    "auto-video": {
        "name": "🎬 Portal Video Creator",
        "description": "Generate videos via ComfyUI / Wan2.2",
        "model_hint": "dolphin-llama3:8b",
    },
    "auto-music": {
        "name": "🎵 Portal Music Producer",
        "description": "Generate music and audio via AudioCraft/MusicGen",
        "model_hint": "dolphin-llama3:8b",
    },
    "auto-research": {
        "name": "🔍 Portal Research Assistant",
        "description": "Web research, information synthesis, fact-checking",
        "model_hint": "deepseek-r1:32b-q4_k_m",
    },
    "auto-vision": {
        "name": "👁️  Portal Vision",
        "description": "Image understanding, visual analysis, multimodal tasks",
        "model_hint": "qwen3-vl:32b",
    },
    "auto-data": {
        "name": "📊 Portal Data Analyst",
        "description": "Data analysis, statistics, visualization guidance",
        "model_hint": "deepseek-r1:32b-q4_k_m",
    },
    "auto-compliance": {
        "name": "⚖️  Portal Compliance Analyst",
        "description": (
            "NERC CIP gap analysis, policy-to-standard mapping, audit evidence review. "
            "Cite exact requirement numbers. Flag ambiguous policy language. "
            "Output structured gap tables with remediation steps."
        ),
        "model_hint": "mlx-community/Qwen3.5-35B-A3B-4bit",
    },
}

# ── Content-aware routing keyword sets ───────────────────────────────────────
# Applied only when the user selects the 'auto' workspace.
# Each set maps to a workspace. Order matters — security before coding
# so "write an exploit in Python" routes to security, not coding.

_SECURITY_KEYWORDS: frozenset[str] = frozenset(
    {
        # Offensive / redteam
        "exploit",
        "payload",
        "shellcode",
        "privilege escalation",
        "privesc",
        "reverse shell",
        "bind shell",
        "command injection",
        "sql injection",
        "sqli",
        "xss",
        "csrf",
        "buffer overflow",
        "rop chain",
        "heap spray",
        "use after free",
        "uaf",
        "zero day",
        "0day",
        "cve-",
        "metasploit",
        "msfvenom",
        "meterpreter",
        "cobalt strike",
        "c2 server",
        "c&c",
        "lateral movement",
        "persistence mechanism",
        "evasion",
        "obfuscation",
        "antivirus bypass",
        "edr bypass",
        "av evasion",
        "defense evasion",
        "exfiltration",
        "data exfiltration",
        "lolbas",
        "living off the land",
        "pentesting",
        "pentest",
        "penetration test",
        "red team",
        "redteam",
        "offensive security",
        "bug bounty",
        "ctf",
        "capture the flag",
        "nmap",
        "masscan",
        "gobuster",
        "nikto",
        "burp suite",
        "sqlmap",
        "hydra",
        "hashcat",
        "mimikatz",
        "bloodhound",
        "crackmapexec",
        "pass the hash",
        "pass the ticket",
        "kerberoasting",
        "asreproasting",
        "golden ticket",
        "silver ticket",
        "dcsync",
        # Defensive / blue team
        "incident response",
        "threat hunting",
        "threat intelligence",
        "ioc",
        "indicator of compromise",
        "malware analysis",
        "reverse engineering",
        "yara rule",
        "sigma rule",
        "siem alert",
        "splunk detection",
        "ids rule",
        "snort rule",
        "suricata",
        "network forensics",
        "memory forensics",
        "volatility",
        "malware",
        "ransomware",
        "trojan",
        "rootkit",
        "backdoor",
        "botnet",
        "threat actor",
        "vulnerability assessment",
        "vulnerability scan",
        "nessus",
        "openvas",
        "security audit",
        "hardening",
        "cis benchmark",
        "mitre att&ck",
        "attack framework",
        "kill chain",
        "diamond model",
    }
)

_REDTEAM_KEYWORDS: frozenset[str] = frozenset(
    {
        # Clearly offensive intent — route to redteam (more permissive model)
        "exploit",
        "payload",
        "shellcode",
        "bypass",
        "evasion",
        "obfuscate",
        "reverse shell",
        "bind shell",
        "privilege escalation",
        "privesc",
        "c2",
        "c2 server",
        "command and control",
        "metasploit",
        "msfvenom",
        "cobalt strike",
        "offensive",
        "red team",
        "redteam",
        "pentest",
        "penetration test",
        "hack",
        "hacking",
        "ctf",
        "lolbas",
        "living off",
        "lateral movement",
        "mimikatz",
        "bloodhound",
        "dcsync",
        "kerberoast",
        "pass the hash",
        "golden ticket",
        "edr bypass",
        "av evasion",
        "antivirus bypass",
    }
)

_CODING_KEYWORDS: frozenset[str] = frozenset(
    {
        "write a function",
        "write a script",
        "write a program",
        "write code",
        "debug this",
        "fix this code",
        "fix the bug",
        "code review",
        "refactor",
        "implement",
        "class definition",
        "api endpoint",
        "unit test",
        "pytest",
        "unittest",
        "docker",
        "kubernetes",
        "ci/cd",
        "sql query",
        "regex",
        "algorithm",
        "data structure",
        "python",
        "javascript",
        "typescript",
        "rust",
        "golang",
        "bash script",
        "powershell",
        "ansible",
        "terraform",
        "splunk",
        "spl query",
        "bigfix",
        "bes xml",
        "relevance",
    }
)

_REASONING_KEYWORDS: frozenset[str] = frozenset(
    {
        "analyze",
        "compare",
        "evaluate",
        "pros and cons",
        "trade-off",
        "research",
        "summarize",
        "explain in depth",
        "step by step",
        "break down",
        "how does",
        "why does",
        "what is the difference",
        "deep dive",
        "comprehensive",
        "thorough",
        "detailed analysis",
    }
)


# P9: Pre-compiled regex for security and coding keyword sets.
# Replaces 80+/35+ substring scans with a single regex match pass.
# Pattern: \b(word1|word2|...)\b — word boundary prevents partial matches.
def _make_word_boundary_regex(keywords: frozenset[str]) -> re.Pattern:
    escaped = [re.escape(kw) for kw in keywords]
    pattern = r"\b(" + "|".join(escaped) + r")\b"
    return re.compile(pattern, re.IGNORECASE)


_SECURITY_REGEX = _make_word_boundary_regex(_SECURITY_KEYWORDS)
_CODING_REGEX = _make_word_boundary_regex(_CODING_KEYWORDS)


def _detect_workspace(messages: list[dict]) -> str | None:
    """Detect the most appropriate workspace from the last user message.

    Returns a workspace ID string, or None if no strong signal found
    (caller should use the default 'auto' routing in that case).

    Routing priority (highest to lowest):
    1. Redteam keywords → auto-redteam (most permissive security model)
    2. Security keywords → auto-security (defensive + offensive analysis)
    3. Coding keywords → auto-coding (Qwen3-Coder-Next via MLX)
    4. Reasoning keywords → auto-reasoning (DeepSeek-R1)
    """
    # Find the last user message — reversed() stops at first hit (O(1) for recent msgs)
    last_user_content = ""
    for msg in reversed(messages):
        if msg.get("role") == "user":
            last_user_content = str(msg.get("content", ""))[:2000].lower()
            break

    if not last_user_content:
        return None

    # Redteam check first — more specific than security (needs 2 hits).
    # Early-exit loop: stop scanning as soon as threshold is met.
    redteam_hits = 0
    for kw in _REDTEAM_KEYWORDS:
        if kw in last_user_content:
            redteam_hits += 1
            if redteam_hits >= 2:
                return "auto-redteam"

    # Security check (broader — includes defensive topics). 1 hit is enough.
    # Pre-compiled regex (P9): single pass instead of 100+ substring scans.
    if _SECURITY_REGEX.search(last_user_content):
        return "auto-security"

    # Coding check — same single-pass regex (P9).
    if _CODING_REGEX.search(last_user_content):
        return "auto-coding"

    # Reasoning check (requires 2+ signals to avoid false positives).
    reasoning_hits = 0
    for kw in _REASONING_KEYWORDS:
        if kw in last_user_content:
            reasoning_hits += 1
            if reasoning_hits >= 2:
                return "auto-reasoning"

    return None


_raw_api_key = os.environ.get("PIPELINE_API_KEY", "")
if not _raw_api_key:
    import warnings

    warnings.warn(
        "PIPELINE_API_KEY is not set — using insecure default 'portal-pipeline'. "
        "Set PIPELINE_API_KEY in .env before deploying.",
        stacklevel=1,
    )
    _raw_api_key = "portal-pipeline"
PIPELINE_API_KEY: str = _raw_api_key

# Concurrency limiter — prevents Ollama overload when all workers are busy
_MAX_CONCURRENT = int(os.environ.get("MAX_CONCURRENT_REQUESTS", "20"))

# Semaphore acquisition timeout in milliseconds. Default 50ms survives normal
# scheduling jitter. Set to 0 to restore original 1ms non-blocking behavior.
try:
    _SEMAPHORE_TIMEOUT = float(os.environ.get("SEMAPHORE_TIMEOUT_MS", "50")) / 1000.0
except ValueError:
    _SEMAPHORE_TIMEOUT = 0.050
    logger.warning("Invalid SEMAPHORE_TIMEOUT_MS value — must be a number. Using default: 50ms")
_request_semaphore: asyncio.Semaphore | None = None

# ── Ollama per-request TTFT tuning ────────────────────────────────────────────
# keep_alive: how long Ollama keeps the model loaded after a request completes.
#   "-1" = never unload. Eliminates the 10-30s cold-start on the next request.
#   Native Ollama default is ~5 min; docker-ollama sets OLLAMA_KEEP_ALIVE=24h
#   server-wide, but native installs don't get that. Injecting it per-request
#   covers both cases reliably.
# num_batch: tokens processed per prompt-evaluation pass (Ollama default: 512).
#   2048 = 4× throughput during prefill — cuts TTFT on long conversation histories.
#   Safe upper bound: match your model's training context / 8. 2048 fits all
#   models in the catalog without exceeding their attention window.
_OLLAMA_KEEP_ALIVE: str = os.environ.get("OLLAMA_KEEP_ALIVE_REQUEST", "-1")
try:
    _OLLAMA_NUM_BATCH: int = int(os.environ.get("OLLAMA_NUM_BATCH", "2048"))
except ValueError:
    _OLLAMA_NUM_BATCH = 2048
    logger.warning(
        "Invalid OLLAMA_NUM_BATCH value — must be an integer. Using default: %d", _OLLAMA_NUM_BATCH
    )

# ── Routing visibility ─────────────────────────────────────────────────────────
# When true, the first line of every streaming response shows which workspace and
# model was selected. Set SHOW_ROUTING_STATUS=true in .env to enable.
# Default false — clean output. Useful for debugging auto-routing decisions.
_SHOW_ROUTING_STATUS: bool = os.environ.get("SHOW_ROUTING_STATUS", "false").lower() in (
    "1",
    "true",
    "yes",
)

registry: BackendRegistry | None = None
_health_task: asyncio.Task | None = None

# Shared httpx client for backend inference — P1: connection pool reused across
# all streaming and completion requests, avoiding TCP/TLS handshake overhead.
_http_client: httpx.AsyncClient | None = None


def _inject_ollama_options(body: dict) -> dict:
    """Inject Ollama-specific TTFT performance defaults not already in the request.

    Only called for backends with type='ollama'. Skipped for MLX and vLLM which
    do not recognise these fields.

    - keep_alive: top-level Ollama field. Prevents model unloading between
      requests, eliminating the 10-30s cold-start on the next request.
    - num_batch: inside 'options'. Larger batch = faster prompt evaluation = lower
      TTFT on multi-turn conversations with long histories.

    Uses setdefault() throughout — never overrides an explicit value from the
    caller (e.g. Open WebUI passing its own keep_alive).
    """
    body = dict(body)
    body.setdefault("keep_alive", _OLLAMA_KEEP_ALIVE)
    opts: dict = dict(body.get("options") or {})
    opts.setdefault("num_batch", _OLLAMA_NUM_BATCH)
    body["options"] = opts
    return body


def _init_notifications(registry: BackendRegistry) -> None:
    """Initialize the notification dispatcher and scheduler."""
    global _notification_dispatcher, _notification_scheduler
    # Late import to avoid circular dependency — notifications imports cluster_backends
    from portal_pipeline.notifications import NotificationDispatcher, NotificationScheduler
    from portal_pipeline.notifications.channels import (
        EmailChannel,
        PushoverChannel,
        SlackChannel,
        TelegramChannel,
        WebhookChannel,
    )

    _notification_dispatcher = NotificationDispatcher()

    # Register configured channels — share the pipeline's HTTP connection pool
    _notification_dispatcher.add_channel(SlackChannel(_http_client))
    _notification_dispatcher.add_channel(TelegramChannel(_http_client))
    _notification_dispatcher.add_channel(EmailChannel(_http_client))
    _notification_dispatcher.add_channel(PushoverChannel(_http_client))
    _notification_dispatcher.add_channel(WebhookChannel(_http_client))

    # Run threshold check on first health cycle to catch any immediate issues
    _notification_dispatcher.check_thresholds_and_alert(registry)

    # Schedule daily summary
    _notification_scheduler = NotificationScheduler(_notification_dispatcher)
    _notification_scheduler.start()

    # Attach scheduler to pipeline metrics for summary building
    from portal_pipeline.notifications import scheduler as notif_scheduler

    notif_scheduler._attach_to_pipeline(
        _notification_dispatcher,
        _request_count,
        _startup_time,
        registry,
    )


async def _warmup_auto_model(registry: BackendRegistry) -> None:
    """Pre-load the auto workspace's default model on startup.

    Ollama lazily loads models on first request. A cold load of an 8B model
    takes 10-30s on HDD, 1-5s on SSD/NFS. By making a minimal generation call
    during startup, subsequent user requests skip this penalty entirely.

    Runs in the background — startup is not blocked. Errors are logged but
    swallowed so a failed warmup does not crash the pipeline.
    """
    if _http_client is None:
        logger.debug("Warmup skipped: HTTP client not ready")
        return
    try:
        backend = registry.get_backend_for_workspace("auto")
        if backend is None:
            logger.debug("Warmup skipped: no healthy auto backend")
            return

        # Minimal prompt: one token of output, fastest model already in memory
        warmup_payload = {
            "model": backend.models[0] if backend.models else "dolphin-llama3:8b",
            "prompt": "ok",
            "stream": False,
            "options": {"num_predict": 1},
        }

        resp = await _http_client.post(backend.chat_url, json=warmup_payload)
        if resp.status_code == 200:
            logger.info(
                "Warmup complete: %s model '%s' pre-loaded",
                backend.type,
                warmup_payload["model"],
            )
        else:
            logger.debug(
                "Warmup backend %s returned HTTP %d — will load on first use",
                backend.id,
                resp.status_code,
            )
    except Exception as e:
        # Never let warmup failure affect pipeline startup
        logger.debug("Model warmup failed (non-fatal): %s", e)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    global registry, _health_task, _request_semaphore, _http_client
    global _notification_dispatcher, _notification_scheduler
    _request_semaphore = asyncio.Semaphore(_MAX_CONCURRENT)
    # P1: create shared client with a connection pool sized for concurrent inference
    _http_client = httpx.AsyncClient(
        timeout=httpx.Timeout(120.0, connect=5.0),
        limits=httpx.Limits(
            max_keepalive_connections=20,
            max_connections=100,
        ),
    )
    registry = BackendRegistry()
    await registry.health_check_all()
    # Pre-warm: load the auto workspace's default model so the first user request
    # is not penalized by Ollama's model-loading cold-start (10-60s for 8-32B).
    asyncio.create_task(_warmup_auto_model(registry))
    healthy = registry.list_healthy_backends()
    logger.info("Portal Pipeline started. Healthy backends: %d", len(healthy))
    if not healthy:
        logger.warning(
            "No healthy backends on startup — check Ollama is running and "
            "config/backends.yaml URLs are reachable from this container"
        )

    # ── Notifications: alerts + daily summaries ──────────────────────────────
    if os.environ.get("NOTIFICATIONS_ENABLED", "false").lower() in ("true", "1", "yes"):
        _init_notifications(registry)

    _health_task = asyncio.create_task(
        registry.start_health_loop(
            on_health_check=(
                lambda r: (
                    _notification_dispatcher.check_thresholds_and_alert(r)
                    if _notification_dispatcher
                    else None
                )
            )
        )
    )

    yield
    if _health_task:
        _health_task.cancel()
    if _http_client:
        await _http_client.aclose()
    if _notification_scheduler:
        _notification_scheduler.stop()
    await BackendRegistry.close_health_client()


try:
    _PKG_VERSION = importlib.metadata.version("portal-5")
except importlib.metadata.PackageNotFoundError:
    _PKG_VERSION = "dev"
app = FastAPI(title="Portal Pipeline", version=_PKG_VERSION, lifespan=lifespan)


def _verify_key(authorization: str | None) -> None:
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing Authorization header")
    token = authorization.removeprefix("Bearer ").strip()
    if not hmac.compare_digest(token.encode(), PIPELINE_API_KEY.encode()):
        raise HTTPException(status_code=401, detail="Invalid API key")


@app.get("/health")
async def health() -> dict:
    if registry is None:
        raise HTTPException(status_code=503, detail="Backend registry not initialised")
    healthy = registry.list_healthy_backends()
    return {
        "status": "ok" if healthy else "degraded",
        "backends_healthy": len(healthy),
        "backends_total": len(registry.list_backends()),
        "workspaces": len(WORKSPACES),
    }


@app.post("/notifications/test")
async def test_notifications(authorization: str | None = Header(None)) -> dict:
    """Fire a test alert and summary to verify notification channel configuration.

    Returns the status of each configured channel (sent / skipped / error).
    Requires NOTIFICATIONS_ENABLED=true and at least one channel configured.
    """
    _verify_key(authorization)

    if _notification_dispatcher is None:
        raise HTTPException(
            status_code=503,
            detail="Notification dispatcher not initialized (NOTIFICATIONS_ENABLED=false?)",
        )

    from portal_pipeline.notifications.events import AlertEvent, EventType, SummaryEvent

    results: dict[str, str] = {}

    # Fire a test alert
    alert = AlertEvent(
        type=EventType.BACKEND_DOWN,
        message="This is a test alert — Portal 5 notification test successful!",
        backend_id="test-backend",
    )
    try:
        await _notification_dispatcher.dispatch(alert)
        results["alert"] = "dispatched"
    except Exception as e:
        results["alert"] = f"error: {e}"

    # Fire a test summary (stats will be zeros/minimal for a test)
    summary = SummaryEvent(
        timestamp=datetime.now(timezone.utc),
        total_requests=sum(_request_count.values()),
        requests_by_workspace=dict(_request_count),
        healthy_backends=len(registry.list_healthy_backends()) if registry else 0,
        total_backends=len(registry.list_backends()) if registry else 0,
        uptime_seconds=time.time() - _startup_time if _startup_time else 0.0,
        requests_by_model=dict(_req_count_by_model),
        avg_tokens_per_second=0.0,
        total_input_tokens=0,
        total_output_tokens=0,
        avg_response_time_ms=0.0,
    )
    try:
        await _notification_dispatcher.dispatch(summary)
        results["summary"] = "dispatched"
    except Exception as e:
        results["summary"] = f"error: {e}"

    # Report per-channel configuration status
    results["channels"] = {
        "slack": "configured" if os.environ.get("SLACK_ALERT_WEBHOOK_URL") else "not configured",
        "telegram": "configured"
        if os.environ.get("TELEGRAM_ALERT_BOT_TOKEN")
        else "not configured",
        "email": "configured" if os.environ.get("SMTP_HOST") else "not configured",
        "pushover": "configured"
        if (os.environ.get("PUSHOVER_API_TOKEN") and os.environ.get("PUSHOVER_USER_KEY"))
        else "not configured",
        "webhook": "configured" if os.environ.get("WEBHOOK_URL") else "not configured",
    }

    # Report scheduler settings
    results["scheduler"] = {
        "enabled": os.environ.get("ALERT_SUMMARY_ENABLED", "true").lower() in ("true", "1", "yes"),
        "hour": int(os.environ.get("ALERT_SUMMARY_HOUR", "9")),
        "timezone": os.environ.get("ALERT_SUMMARY_TIMEZONE", "UTC"),
    }

    return {"status": "ok", "results": results}


@app.get("/metrics")
async def metrics() -> PlainTextResponse:
    """Prometheus-compatible metrics endpoint.

    Note: request counters are per-worker when PIPELINE_WORKERS > 1.
    For aggregate counts, sum across scrape intervals or set PIPELINE_WORKERS=1.

    Intentionally unauthenticated — Prometheus scrapes without credentials.
    """
    uptime = time.time() - _startup_time
    lines = [
        "# HELP portal_requests_total Total requests by workspace (per-worker when workers>1)",
        "# TYPE portal_requests_total counter",
    ]
    for ws_id, count in _request_count.items():
        lines.append(f'portal_requests_total{{workspace="{ws_id}"}} {count}')

    if registry is None:
        raise HTTPException(status_code=503, detail="Backend registry not initialised")
    healthy = len(registry.list_healthy_backends())
    total = len(registry.list_backends())

    lines += [
        "# HELP portal_backends_healthy Number of healthy backends",
        "# TYPE portal_backends_healthy gauge",
        f"portal_backends_healthy {healthy}",
        "# HELP portal_backends_total Total registered backends",
        "# TYPE portal_backends_total gauge",
        f"portal_backends_total {total}",
        "# HELP portal_uptime_seconds Process uptime in seconds",
        "# TYPE portal_uptime_seconds gauge",
        f"portal_uptime_seconds {uptime:.1f}",
        "# HELP portal_workspaces_total Number of configured workspaces",
        "# TYPE portal_workspaces_total gauge",
        f"portal_workspaces_total {len(WORKSPACES)}",
    ]
    # Combine hand-rolled metrics with prometheus_client metrics.
    # Use multiprocess collector when PROMETHEUS_MULTIPROC_DIR is set
    # (aggregates metrics across all uvicorn workers).
    # Cache the registry object — MultiProcessCollector reads from disk files,
    # so there's no need to reconstruct it on every scrape.
    global _mp_registry_cache, _mp_registry_dir_cache
    mp_dir = os.environ.get("PROMETHEUS_MULTIPROC_DIR")
    if mp_dir:
        if _mp_registry_cache is None or _mp_registry_dir_cache != mp_dir:
            from prometheus_client import multiprocess

            _mp_registry_cache = CollectorRegistry()
            multiprocess.MultiProcessCollector(_mp_registry_cache)
            _mp_registry_dir_cache = mp_dir
        prometheus_output = generate_latest(_mp_registry_cache).decode("utf-8")
    else:
        prometheus_output = generate_latest(_REGISTRY).decode("utf-8")
    return PlainTextResponse("\n".join(lines) + "\n" + prometheus_output)


@app.get("/v1/models")
async def list_models(authorization: str | None = Header(None)) -> dict:
    _verify_key(authorization)
    ts = int(time.time())
    models = [
        {
            "id": ws_id,
            "object": "model",
            "created": ts,
            "owned_by": "portal-5",
            "name": ws_cfg["name"],
            "description": ws_cfg["description"],
        }
        for ws_id, ws_cfg in WORKSPACES.items()
    ]
    return {"object": "list", "data": models}


async def _try_non_streaming(
    backend: Any,
    body: dict,
    workspace_id: str,
    *,
    enforce_hint: bool = True,
) -> JSONResponse | None:
    """Try non-streaming completion from a single backend.

    Returns JSONResponse on success, None on failure (caller tries next backend).
    When enforce_hint=True and the workspace has a model_hint, backends that
    don't carry the hinted model are skipped (returns None) so the loop tries
    the next backend. Set enforce_hint=False on the last candidate to accept
    any model as fallback.
    """
    if _http_client is None:
        return None
    ws_cfg = WORKSPACES.get(workspace_id, {})
    model_hint = ws_cfg.get("model_hint", "")
    if model_hint and model_hint in backend.models:
        target_model = model_hint
    elif model_hint and enforce_hint and backend.type != "mlx":
        # Non-MLX backend doesn't have the hinted model — skip to try next backend.
        # MLX backends are never skipped: server switching ensures the right model loads.
        logger.debug(
            "Backend %s lacks hinted model %s for workspace=%s — skipping",
            backend.id,
            model_hint,
            workspace_id,
        )
        return None
    else:
        target_model = backend.models[0] if backend.models else "dolphin-llama3:8b"
    req_body = {**body, "model": target_model, "stream": False}
    if backend.type == "ollama":
        req_body = _inject_ollama_options(req_body)

    try:
        resp = await _http_client.post(backend.chat_url, json=req_body)
        resp.raise_for_status()
        data = resp.json()
        _record_usage(model=target_model, workspace=workspace_id, data=data)
        logger.info(
            "Backend %s succeeded for workspace=%s model=%s",
            backend.id,
            workspace_id,
            target_model,
        )
        return JSONResponse(content=data)
    except Exception as e:
        logger.warning(
            "Backend %s failed for workspace=%s: %s — trying next candidate",
            backend.id,
            workspace_id,
            e,
        )
        return None


@app.post("/v1/chat/completions")
async def chat_completions(
    request: Request,
    authorization: str | None = Header(None),
) -> Any:
    _verify_key(authorization)

    content_length = int(request.headers.get("content-length", 0))
    if content_length > _MAX_REQUEST_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"Request body too large (max {_MAX_REQUEST_BYTES // 1024 // 1024}MB)",
        )

    if _request_semaphore is None:
        raise HTTPException(status_code=503, detail="Request semaphore not initialised")
    try:
        await asyncio.wait_for(_request_semaphore.acquire(), timeout=_SEMAPHORE_TIMEOUT)
    except asyncio.TimeoutError:
        raise HTTPException(
            status_code=503,
            detail="Server busy — too many concurrent requests. Please retry.",
            headers={"Retry-After": "5"},
        ) from None

    _is_streaming = False
    start_time = time.monotonic()  # Track request start for response time measurement
    try:
        if registry is None:
            raise HTTPException(status_code=503, detail="Backend registry not initialised")

        body = await request.json()
        workspace_id = body.get("model") or "auto"
        stream = body.get("stream", True)

        # Content-aware routing for 'auto' workspace
        # Inspect message content to pick the most specialized backend.
        # This lets users ask security/coding/reasoning questions through 'auto'
        # and get the right specialist model without manually switching workspaces.
        if workspace_id == "auto":
            messages = body.get("messages", [])
            detected = _detect_workspace(messages)
            if detected:
                logger.info("Auto-routing: detected workspace '%s' from message content", detected)
                workspace_id = detected

        _request_count[workspace_id] = _request_count.get(workspace_id, 0) + 1

        candidates = registry.get_backend_candidates(workspace_id)
        if not candidates:
            raise HTTPException(
                status_code=503,
                detail=(
                    "No healthy backends available. "
                    "Ensure Ollama is running and a model is pulled. "
                    "Check config/backends.yaml."
                ),
            )

        if not stream:
            # Non-streaming: try each backend in priority order until one succeeds.
            # Model hint is enforced (skip backends without the hinted model) for
            # all but the last candidate, where we accept any model as fallback.
            for i, backend in enumerate(candidates):
                is_last = i == len(candidates) - 1
                result = await _try_non_streaming(
                    backend, body, workspace_id, enforce_hint=not is_last
                )
                if result is not None:
                    _record_response_time(
                        backend.models[0] if backend.models else "unknown",
                        workspace_id,
                        time.monotonic() - start_time,
                    )
                    return result
            # All backends failed
            raise HTTPException(
                status_code=502,
                detail="All backends failed — check server logs",
            )

        # Streaming: try first backend. If the stream yields an error chunk early,
        # fall back to non-streaming with remaining candidates.
        backend = candidates[0]
        ws_cfg = WORKSPACES.get(workspace_id, {})
        model_hint = ws_cfg.get("model_hint", "")
        if model_hint and model_hint in backend.models:
            target_model = model_hint
        else:
            target_model = backend.models[0] if backend.models else "dolphin-llama3:8b"

        backend_body = {**body, "model": target_model}

        # Inject keep_alive + num_batch for Ollama backends.
        # Skipped for MLX (doesn't accept these fields) and vLLM (uses its own config).
        if backend.type == "ollama":
            backend_body = _inject_ollama_options(backend_body)

        logger.info(
            "Routing workspace=%s → backend=%s model=%s stream=%s (1/%d candidates)",
            workspace_id,
            backend.id,
            target_model,
            stream,
            len(candidates),
        )

        if len(candidates) == 1:
            # Single candidate — no fallback possible, return streaming directly
            _streaming_response = StreamingResponse(
                _stream_with_preamble(
                    backend.chat_url,
                    backend_body,
                    _request_semaphore,
                    workspace_id=workspace_id,
                    model=target_model,
                    start_time=start_time,
                ),
                media_type="text/event-stream",
            )
            _is_streaming = True
            return _streaming_response

        # Multiple candidates — streaming with non-streaming fallback.
        # Try streaming from first backend; if it fails, fall back to non-streaming
        # from the remaining candidates.
        remaining = candidates[1:]

        async def _stream_or_fallback() -> AsyncIterator[bytes]:
            stream_failed = False
            try:
                async for chunk in _stream_with_preamble(
                    backend.chat_url,
                    backend_body,
                    _request_semaphore,
                    workspace_id=workspace_id,
                    model=target_model,
                    start_time=start_time,
                ):
                    if b'"error"' in chunk:
                        stream_failed = True
                    yield chunk
            except Exception:
                stream_failed = True

            if stream_failed and remaining:
                logger.info(
                    "Stream from %s failed, falling back to non-streaming for workspace=%s",
                    backend.id,
                    workspace_id,
                )
                fallback_body = {**body, "stream": False}
                for j, fb in enumerate(remaining):
                    fb_last = j == len(remaining) - 1
                    result = await _try_non_streaming(
                        fb, fallback_body, workspace_id, enforce_hint=not fb_last
                    )
                    if result is not None:
                        # Wrap non-streaming response as SSE for Open WebUI
                        import json as _json

                        data = _json.loads(result.body)
                        ts = int(time.time())
                        rid = f"chatcmpl-p5-{ts}"
                        # Emit role chunk
                        role_payload = {
                            "id": rid,
                            "object": "chat.completion.chunk",
                            "created": ts,
                            "model": workspace_id,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {"role": "assistant", "content": ""},
                                    "finish_reason": None,
                                }
                            ],
                        }
                        yield f"data: {_json.dumps(role_payload)}\n\n".encode()
                        # Emit content chunk
                        content = ""
                        if "choices" in data and data["choices"]:
                            msg = data["choices"][0].get("message", {})
                            content = msg.get("content", "")
                        if content:
                            content_payload = {
                                "id": rid,
                                "object": "chat.completion.chunk",
                                "created": ts,
                                "model": workspace_id,
                                "choices": [
                                    {
                                        "index": 0,
                                        "delta": {"content": content},
                                        "finish_reason": None,
                                    }
                                ],
                            }
                            yield f"data: {_json.dumps(content_payload)}\n\n".encode()
                        # Emit done
                        done_payload = {
                            "id": rid,
                            "object": "chat.completion.chunk",
                            "created": ts,
                            "model": workspace_id,
                            "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
                        }
                        yield f"data: {_json.dumps(done_payload)}\n\n".encode()
                        yield b"data: [DONE]\n\n"
                        return

        _streaming_response = StreamingResponse(
            _stream_or_fallback(),
            media_type="text/event-stream",
        )
        _is_streaming = True
        return _streaming_response
    finally:
        if not _is_streaming:
            # Non-streaming: response fully awaited above, safe to release here
            # Streaming: generator releases after stream completes
            _request_semaphore.release()


async def _stream_with_preamble(
    url: str,
    body: dict,
    sem: asyncio.Semaphore,
    workspace_id: str = "unknown",
    model: str = "unknown",
    start_time: float | None = None,
) -> AsyncIterator[bytes]:
    """Emit an immediate OpenAI role chunk before connecting to the backend.

    Problem: without this, Open WebUI shows nothing (frozen input, no typing
    indicator) until Ollama returns its first token. That wait includes model
    load time (10-30s cold start) plus prompt prefill — entirely silent from
    the user's perspective.

    Fix: yield a valid OpenAI streaming chunk immediately. FastAPI flushes this
    to the client before the backend connection is even opened, causing Open WebUI
    to show the typing indicator and mark the response as started. The actual
    backend response follows as normal.

    The preamble chunk carries an empty delta content — it adds no visible text to
    the chat. If SHOW_ROUTING_STATUS=true, a second chunk annotates the response
    with the selected workspace and model name.
    """
    ts = int(time.time())
    request_id = f"chatcmpl-p5-{ts}"

    def _make_chunk(delta: dict) -> bytes:
        """Serialise a single OpenAI-compatible SSE chunk."""
        payload = {
            "id": request_id,
            "object": "chat.completion.chunk",
            "created": ts,
            "model": workspace_id,
            "choices": [{"index": 0, "delta": delta, "finish_reason": None}],
        }
        return f"data: {json.dumps(payload)}\n\n".encode()

    # Empty role chunk — starts Open WebUI typing indicator with zero latency.
    yield _make_chunk({"role": "assistant", "content": ""})

    # Optional routing annotation — shows workspace + model at top of response.
    if _SHOW_ROUTING_STATUS:
        ws_name = WORKSPACES.get(workspace_id, {}).get("name", workspace_id)
        yield _make_chunk({"content": f"`⚡ {ws_name} → {model}`\n\n"})

    # Stream from backend.
    # Semaphore ownership: _stream_with_preamble owns sem and releases it in its
    # own finally block (below). _stream_from_backend_guarded is called with
    # sem=None so its finally does NOT also release — preventing double-release.
    # This closes the window where a client disconnect after the preamble yield but
    # before the backend stream starts would leave sem permanently acquired.
    try:
        async for chunk in _stream_from_backend_guarded(
            url, body, sem=None, workspace_id=workspace_id, model=model, start_time=start_time
        ):
            yield chunk
    finally:
        sem.release()


async def _stream_from_backend_guarded(
    url: str,
    body: dict,
    sem: asyncio.Semaphore | None,
    workspace_id: str = "unknown",
    model: str = "unknown",
    start_time: float | None = None,
) -> AsyncIterator[bytes]:
    """Stream from backend and optionally release semaphore when stream is complete.

    sem=None: caller (e.g. _stream_with_preamble) owns semaphore release.
    sem=Semaphore: this function releases it in its finally block.

    The sem=None path exists so _stream_with_preamble can own the full semaphore
    lifecycle via its own try/finally, closing the early-disconnect leak window.
    """
    if _http_client is None:
        logger.error("HTTP client not initialised — yielding error chunk")
        yield ("data: " + json.dumps({"error": "Pipeline not ready"}) + "\n\n").encode()
        if sem is not None:
            sem.release()
        return
    try:
        async with _http_client.stream("POST", url, json=body) as resp:
            if resp.status_code != 200:
                err = await resp.aread()
                logger.error(
                    "Backend %s returned HTTP %d: %s",
                    url,
                    resp.status_code,
                    err[:200].decode(errors="replace"),
                )
                yield (
                    "data: "
                    + json.dumps({"error": f"Backend returned HTTP {resp.status_code}"})
                    + "\n\n"
                ).encode()
                return
            async for chunk in resp.aiter_bytes():
                if chunk:
                    # P6: Check raw bytes for '"done"' before decode — skip 99% of chunks.
                    if b'"done"' in chunk:
                        chunk_text = chunk.decode("utf-8", errors="replace")
                        for line in chunk_text.splitlines():
                            line = line.strip()
                            if line.startswith("data:") and "done" in line:
                                payload = line[5:].strip()
                                if payload and payload != "[DONE]":
                                    try:
                                        usage_data = json.loads(payload)
                                        elapsed = (
                                            (time.monotonic() - start_time)
                                            if start_time is not None
                                            else None
                                        )
                                        _record_usage(
                                            model=usage_data.get("model", model),
                                            workspace=workspace_id,
                                            data=usage_data,
                                            elapsed_seconds=elapsed,
                                        )
                                    except Exception:
                                        logger.debug("Could not parse usage payload from stream")
                                    break
                    # OpenAI SSE: "data: [DONE]" terminator — no usage data, but record with elapsed time.
                    if b"data: [DONE]" in chunk:
                        elapsed = (
                            (time.monotonic() - start_time) if start_time is not None else None
                        )
                        _record_usage(
                            model=model, workspace=workspace_id, data={}, elapsed_seconds=elapsed
                        )
                    yield chunk
    except Exception as e:
        logger.error("Stream error from %s: %s", url, e)
        yield (
            "data: "
            + json.dumps({"error": "Backend connection error — check server logs"})
            + "\n\n"
        ).encode()
    finally:
        if start_time is not None:
            _record_response_time(model, workspace_id, time.monotonic() - start_time)
        if sem is not None:
            sem.release()  # Release AFTER generator is fully exhausted


async def _complete_from_backend(
    url: str, body: dict, workspace_id: str = "unknown", model: str = "unknown"
) -> JSONResponse:
    if _http_client is None:
        raise HTTPException(status_code=503, detail="Pipeline not ready")
    try:
        resp = await _http_client.post(url, json=body)
        resp.raise_for_status()
        data = resp.json()
        _record_usage(model=model, workspace=workspace_id, data=data)
        return JSONResponse(content=data)
    except Exception as e:
        logger.error("Completion error from %s: %s", url, e)
        raise HTTPException(status_code=502, detail="Backend error — check server logs") from e
