#!/usr/bin/env python3
"""
Open WebUI First-Run Initialization Script

Runs inside the openwebui-init Docker container after Open WebUI is healthy.
Handles:
  1. Admin account creation (first run only — idempotent on re-runs)
  2. MCP Tool Server registration via POST /api/v1/tools/server/
  3. Workspace model preset creation from imports/openwebui/workspaces/
  4. Persona model preset creation from config/personas/*.yaml
  5. User management settings (signup mode, default role)

Environment variables:
  OPENWEBUI_URL              URL of Open WebUI (default: http://open-webui:8080)
  OPENWEBUI_ADMIN_EMAIL      Admin account email (default: admin@portal.local)
  OPENWEBUI_ADMIN_PASSWORD   Admin account password — REQUIRED, generated by launch.sh
  OPENWEBUI_ADMIN_NAME       Admin display name (default: Portal Admin)
  DEFAULT_USER_ROLE          Role for new signups: pending|user|admin (default: pending)
  ENABLE_SIGNUP              Allow self-registration: true|false (default: true)
  FORCE_RESEED               Delete and re-create all presets: true|false (default: false)
                             Use via: ./launch.sh reseed
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import time
from pathlib import Path

import httpx

OPENWEBUI_URL = os.environ.get("OPENWEBUI_URL", "http://open-webui:8080").rstrip("/")
ADMIN_EMAIL = os.environ.get("OPENWEBUI_ADMIN_EMAIL", "admin@portal.local")
ADMIN_PASSWORD = os.environ.get("OPENWEBUI_ADMIN_PASSWORD")
if not ADMIN_PASSWORD:
    raise ValueError("OPENWEBUI_ADMIN_PASSWORD must be set in environment")
ADMIN_NAME = os.environ.get("OPENWEBUI_ADMIN_NAME", "Portal Admin")

# User management settings
DEFAULT_USER_ROLE = os.environ.get("DEFAULT_USER_ROLE", "pending")
ENABLE_SIGNUP = os.environ.get("ENABLE_SIGNUP", "true").lower() == "true"
FORCE_RESEED = os.environ.get("FORCE_RESEED", "false").lower() == "true"

IMPORTS_DIR = Path("/imports/openwebui")
MCP_FILE = IMPORTS_DIR / "mcp-servers.json"
WORKSPACES_DIR = IMPORTS_DIR / "workspaces"
PERSONAS_DIR = Path("/personas")

MAX_WAIT_SECONDS = 120
POLL_INTERVAL = 5


# --- Utilities ---------------------------------------------------------------


def wait_for_openwebui(client: httpx.Client) -> bool:
    """Poll until Open WebUI health endpoint responds."""
    print(f"Waiting for Open WebUI at {OPENWEBUI_URL}...")
    deadline = time.time() + MAX_WAIT_SECONDS
    while time.time() < deadline:
        try:
            resp = client.get(f"{OPENWEBUI_URL}/health", timeout=5.0)
            if resp.status_code == 200:
                print("  Open WebUI is healthy")
                return True
        except Exception:
            pass
        print(f"  Not ready yet - retrying in {POLL_INTERVAL}s...")
        time.sleep(POLL_INTERVAL)
    print("ERROR: Open WebUI did not become ready in time")
    return False


def create_admin_account(client: httpx.Client) -> str | None:
    """Create the admin account. Returns API token or None if already exists."""
    print(f"Creating admin account: {ADMIN_EMAIL}")
    try:
        resp = client.post(
            f"{OPENWEBUI_URL}/api/v1/auths/signup",
            json={
                "name": ADMIN_NAME,
                "email": ADMIN_EMAIL,
                "password": ADMIN_PASSWORD,
            },
            timeout=15.0,
        )
        if resp.status_code in (200, 201):
            token = resp.json().get("token")
            print("  Admin account created")
            return token
        elif resp.status_code == 400:
            # User already exists - this is expected on non-first runs
            detail = resp.json().get("detail", "")
            if "already" in detail.lower() or "exist" in detail.lower():
                print("  Admin account already exists (not first run)")
                return None
            print(f"  Signup failed: {detail}")
            return None
        else:
            print(f"  Signup failed: HTTP {resp.status_code} - {resp.text[:150]}")
            return None
    except Exception as e:
        print(f"  Signup error: {e}")
        return None


def login(client: httpx.Client) -> str | None:
    """Login and return API token."""
    print(f"Logging in as: {ADMIN_EMAIL}")
    try:
        resp = client.post(
            f"{OPENWEBUI_URL}/api/v1/auths/signin",
            json={"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD},
            timeout=15.0,
        )
        if resp.status_code == 200:
            token = resp.json().get("token")
            print("  Login successful")
            return token
        else:
            print(f"  Login failed: HTTP {resp.status_code} - {resp.text[:150]}")
            return None
    except Exception as e:
        print(f"  Login error: {e}")
        return None


def auth_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


# --- Tool Server Registration -------------------------------------------------


async def register_tool_servers_async(client: httpx.AsyncClient, token: str) -> None:
    """Register all Portal MCP servers as Tool Servers in Open WebUI.

    OW 0.8.x API: GET/POST /api/v1/configs/tool_servers replaces the old
    per-server /api/v1/tools/server/ endpoint. We fetch the current list,
    add any missing servers, and POST the full list back.
    """
    print("\nRegistering MCP Tool Servers...")

    if not MCP_FILE.exists():
        print(f"  Skipping - {MCP_FILE} not found")
        return

    servers = json.loads(MCP_FILE.read_text()).get("tool_servers", [])
    if not servers:
        print("  Skipping - no tool_servers in mcp-servers.json")
        return

    # Get current connections
    current_connections: list[dict] = []
    try:
        resp = await client.get(
            f"{OPENWEBUI_URL}/api/v1/configs/tool_servers",
            headers=auth_headers(token),
        )
        if resp.status_code == 200:
            current_connections = resp.json().get("TOOL_SERVER_CONNECTIONS", [])
    except Exception as e:
        print(f"  Warning: could not fetch existing tool server config: {e}")

    existing_urls = {c.get("url", "") for c in current_connections}

    added = skipped = 0
    for server in servers:
        url = server["url"]
        key = server.get("api_key", "")
        if url in existing_urls:
            print(f"  Skip (exists): {server['name']}")
            skipped += 1
        else:
            current_connections.append({
                "url": url,
                "path": "openapi.json",
                "type": "openapi",
                "auth_type": "none" if not key else "bearer",
                "headers": None,
                "key": key,
                "config": {"enable": True},
            })
            print(f"  Adding: {server['name']}")
            added += 1

    if added > 0:
        try:
            resp = await client.post(
                f"{OPENWEBUI_URL}/api/v1/configs/tool_servers",
                json={"TOOL_SERVER_CONNECTIONS": current_connections},
                headers=auth_headers(token),
                timeout=15.0,
            )
            if resp.status_code in (200, 201):
                print(f"  Done: {added} added, {skipped} skipped")
            else:
                print(f"  Failed to update tool servers: HTTP {resp.status_code}")
        except Exception as e:
            print(f"  Error updating tool servers: {e}")
    else:
        print(f"  Done: all {skipped} servers already registered")


# --- Workspace Creation -------------------------------------------------------


async def create_workspaces_async(client: httpx.AsyncClient, token: str) -> None:
    """Create Portal workspace presets in Open WebUI."""
    print("\nCreating Workspaces...")

    # Ensure workspace toolIds are current before seeding
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location(
            "update_workspace_tools",
            Path(__file__).parent / "update_workspace_tools.py",
        )
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        if hasattr(mod, "main"):
            mod.main()
    except Exception as e:
        import logging

        logging.getLogger(__name__).warning("Could not update workspace toolIds: %s", e)

    if not WORKSPACES_DIR.exists():
        print(f"  Skipping - {WORKSPACES_DIR} not found")
        return

    ws_files = sorted(WORKSPACES_DIR.glob("workspace_*.json"))
    if not ws_files:
        print("  Skipping - no workspace files found")
        return

    # Get existing workspaces
    # Use /export (not /list) — /list is paginated (30/page) and would miss models beyond page 1
    existing_names: set[str] = set()
    try:
        resp = await client.get(
            f"{OPENWEBUI_URL}/api/v1/models/export",
            headers=auth_headers(token),
        )
        if resp.status_code == 200:
            data = resp.json()
            models = data if isinstance(data, list) else data.get("items", data.get("data", []))
            for m in models:
                existing_names.add(m.get("id", ""))
    except Exception as e:
        print(f"  Warning: could not check existing models: {e}")

    created = updated = failed = 0
    for ws_file in ws_files:
        ws = json.loads(ws_file.read_text())
        ws_id = ws.get("id", "")
        ws_name = ws.get("name", ws_id)

        # base_model_id must be non-null for OW v0.6.5 get_models() to return this preset.
        # Workspaces use their own ID as base since they ARE pipeline-level endpoints.
        ws_base = ws.get("base_model_id") or ws.get("params", {}).get("model") or ws_id
        payload = {
            "id": ws_id,
            "name": ws_name,
            "base_model_id": ws_base,
            "meta": ws.get("meta", {}),
            "params": ws.get("params", {}),
        }

        try:
            if ws_id in existing_names:
                if FORCE_RESEED:
                    # Delete then recreate to ensure all fields are current
                    await client.post(
                        f"{OPENWEBUI_URL}/api/v1/models/model/delete",
                        json={"id": ws_id},
                        headers=auth_headers(token),
                        timeout=10.0,
                    )
                    resp = await client.post(
                        f"{OPENWEBUI_URL}/api/v1/models/create",
                        json=payload,
                        headers=auth_headers(token),
                        timeout=10.0,
                    )
                    if resp.status_code in (200, 201):
                        print(f"  Reseeded: {ws_name}")
                        updated += 1
                    else:
                        print(f"  Reseed failed {ws_name}: HTTP {resp.status_code}")
                        failed += 1
                else:
                    # Update existing workspace to pick up toolIds changes
                    # OW 0.8.x: id is in the request body (ModelForm.id), not a query param
                    resp = await client.post(
                        f"{OPENWEBUI_URL}/api/v1/models/model/update",
                        json=payload,
                        headers=auth_headers(token),
                        timeout=10.0,
                    )
                    if resp.status_code in (200, 201):
                        print(f"  Updated: {ws_name}")
                        updated += 1
                    else:
                        print(f"  Skip (update failed {resp.status_code}): {ws_name}")
            else:
                resp = await client.post(
                    f"{OPENWEBUI_URL}/api/v1/models/create",
                    json=payload,
                    headers=auth_headers(token),
                    timeout=10.0,
                )
                if resp.status_code in (200, 201):
                    print(f"  Created: {ws_name}")
                    created += 1
                else:
                    print(f"  Failed {ws_name}: HTTP {resp.status_code}")
                    failed += 1
        except Exception as e:
            print(f"  Error {ws_name}: {e}")
            failed += 1

    print(f"  Workspaces: {created} created, {updated} updated, {failed} failed")


# --- Persona Presets -----------------------------------------------------------


async def create_persona_presets_async(
    client: httpx.AsyncClient, token: str, personas_dir: Path
) -> None:
    """Create Open WebUI model presets from persona YAML files.

    P5: parallelizes all POSTs via asyncio.gather — faster seeding.
    """
    import yaml as _yaml

    print("\nCreating Persona Model Presets...")
    if not personas_dir.exists():
        print(f"  Skipping — {personas_dir} not found")
        return

    persona_files = sorted(personas_dir.glob("*.yaml"))
    if not persona_files:
        print("  Skipping — no persona YAML files found")
        return

    # Get existing models to avoid duplicates
    # Use /export (not /list) — /list is paginated (30/page) and would miss models beyond page 1
    existing_ids: set[str] = set()
    try:
        resp = await client.get(f"{OPENWEBUI_URL}/api/v1/models/export", headers=auth_headers(token))
        if resp.status_code == 200:
            data = resp.json()
            for m in data if isinstance(data, list) else data.get("items", data.get("data", [])):
                existing_ids.add(m.get("id", ""))
    except Exception as e:
        print(f"  Warning: could not fetch existing models: {e}")

    # Build persona payloads first (file reads, not network I/O)
    persona_payloads = []
    for f in persona_files:
        try:
            persona = _yaml.safe_load(f.read_text())
        except Exception as e:
            print(f"  Skip {f.name}: parse error — {e}")
            continue
        slug = persona.get("slug", f.stem)
        name = persona.get("name", slug)
        system_prompt = persona.get("system_prompt", "")
        workspace_model = persona.get("workspace_model") or "dolphin-llama3:8b"
        persona_payloads.append(
            (
                slug,
                name,
                workspace_model,
                {
                    "id": slug,
                    "name": name,
                    # base_model_id must be non-null for OW v0.6.5 get_models() filter
                    # (WHERE base_model_id IS NOT NULL selects presets vs base models)
                    "base_model_id": workspace_model,
                    "meta": {
                        "description": f"Portal persona: {name}",
                        "profile_image_url": "",
                        "tags": [{"name": persona.get("category", "general")}],
                    },
                    "params": {
                        "system": system_prompt,
                        "model": workspace_model,
                    },
                },
            )
        )

    async def _create_one(
        slug: str, name: str, workspace_model: str, payload: dict
    ) -> tuple[str, str]:
        try:
            if FORCE_RESEED and slug in existing_ids:
                # OW 0.8.x: DELETE endpoint is now POST with JSON body
                await client.post(
                    f"{OPENWEBUI_URL}/api/v1/models/model/delete",
                    json={"id": slug},
                    headers=auth_headers(token),
                    timeout=10.0,
                )
            resp = await client.post(
                f"{OPENWEBUI_URL}/api/v1/models/create",
                json=payload,
                headers=auth_headers(token),
                timeout=10.0,
            )
            if resp.status_code in (200, 201):
                action = "reseeded" if FORCE_RESEED and slug in existing_ids else "created"
                return (name, f"{action}:{workspace_model}")
            return (name, f"fail:{resp.status_code}")
        except Exception as e:
            return (name, f"error:{e}")

    # Create personas in parallel — reseed all if FORCE_RESEED, else skip existing
    if FORCE_RESEED:
        to_create = persona_payloads
        skipped = 0
    else:
        to_create = [
            (slug, name, wm, payload)
            for slug, name, wm, payload in persona_payloads
            if slug not in existing_ids
        ]
        skipped = len(persona_payloads) - len(to_create)

    results = await asyncio.gather(
        *[_create_one(slug, name, wm, payload) for slug, name, wm, payload in to_create],
        return_exceptions=True,
    )

    created = reseeded = failed = 0
    for result in results:
        if isinstance(result, Exception):
            failed += 1
            continue
        name, status = result
        if status.startswith("created:"):
            _, wm = status.split(":", 1)
            print(f"  Created persona: {name} → {wm}")
            created += 1
        elif status.startswith("reseeded:"):
            _, wm = status.split(":", 1)
            print(f"  Reseeded persona: {name} → {wm}")
            reseeded += 1
        else:
            print(f"  Failed {name}: {status}")
            failed += 1

    if FORCE_RESEED:
        print(f"  Done: {reseeded} reseeded, {failed} failed")
    else:
        print(f"  Done: {created} created, {skipped} skipped, {failed} failed")


def configure_user_settings(client: httpx.Client, token: str) -> None:
    """Configure Open WebUI user management settings post-bootstrap."""
    print("\nConfiguring user settings...")

    default_role = DEFAULT_USER_ROLE

    try:
        # OW 0.8.x: signup is configured via admin/config (GET current, PATCH ENABLE_SIGNUP)
        # The old /api/v1/auths/signup/enabled endpoint no longer exists.
        cfg_resp = client.get(
            f"{OPENWEBUI_URL}/api/v1/auths/admin/config",
            headers=auth_headers(token),
            timeout=10.0,
        )
        if cfg_resp.status_code == 200:
            cfg = cfg_resp.json()
            cfg["ENABLE_SIGNUP"] = ENABLE_SIGNUP
            resp = client.post(
                f"{OPENWEBUI_URL}/api/v1/auths/admin/config",
                json=cfg,
                headers=auth_headers(token),
                timeout=10.0,
            )
            if resp.status_code in (200, 201):
                print(f"  Signup enabled: {ENABLE_SIGNUP}")
            else:
                print(f"  Warning: could not set signup mode: HTTP {resp.status_code}")
        else:
            print(f"  Warning: could not fetch admin config: HTTP {cfg_resp.status_code}")
    except Exception as e:
        print(f"  Warning: signup config failed: {e}")

    print(f"  Default user role: {default_role}")
    print("  Note: New users with role 'pending' must be approved by admin at:")
    print(f"        {OPENWEBUI_URL}/admin/users")


def configure_audio_settings(client: httpx.Client, token: str) -> None:
    """Audio TTS/STT is configured via Open WebUI environment variables.

    AUDIO_TTS_ENGINE, AUDIO_TTS_OPENAI_API_BASE_URL, etc. are set in
    docker-compose.yml. No runtime API call needed.
    """
    print(
        "\nAudio settings: configured via environment variables (TTS→mcp-tts:8916, STT→mcp-whisper:8915)"
    )


def configure_tool_settings(client: httpx.Client, token: str) -> None:
    """Tool calling is enabled by default in Open WebUI.

    SAFE_MODE=false in docker-compose.yml env allows full tool access.
    No runtime API call needed — Open WebUI handles this natively.
    The /api/v1/configs/features endpoint does not exist in Open WebUI.
    """
    print("\nTool settings: enabled via SAFE_MODE=false in environment (no API call needed)")


# --- Main ---------------------------------------------------------------------


async def main() -> int:
    client = httpx.Client(timeout=30.0)

    # Wait for Open WebUI to be ready
    if not wait_for_openwebui(client):
        return 1

    # Create admin account (first run) or skip if exists
    token = create_admin_account(client)

    # If signup failed (account exists), login instead
    if token is None:
        token = login(client)

    if not token:
        print("ERROR: Could not obtain API token - check admin credentials in .env")
        print(f"  OPENWEBUI_ADMIN_EMAIL: {ADMIN_EMAIL}")
        print("  Set OPENWEBUI_ADMIN_EMAIL and OPENWEBUI_ADMIN_PASSWORD in .env")
        return 1

    # Seed the instance — P5: parallelize tool servers, workspaces, and persona presets
    # (configure_* are sync print-only helpers, no I/O, so no need to parallelize)
    async_client = httpx.AsyncClient(timeout=30.0)
    try:
        await asyncio.gather(
            register_tool_servers_async(async_client, token),
            create_workspaces_async(async_client, token),
            create_persona_presets_async(async_client, token, PERSONAS_DIR),
        )
    finally:
        await async_client.aclose()

    configure_user_settings(client, token)
    configure_audio_settings(client, token)
    configure_tool_settings(client, token)

    print("\nPortal Open WebUI initialization complete")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
