#!/usr/bin/env python3
"""
Open WebUI First-Run Initialization Script

Runs inside the openwebui-init Docker container after Open WebUI is healthy.
Handles:
  1. Admin account creation (first run only — idempotent on re-runs)
  2. MCP Tool Server registration via POST /api/v1/tools/server/
  3. Workspace model preset creation from imports/openwebui/workspaces/
  4. Persona model preset creation from config/personas/*.yaml
  5. User management settings (signup mode, default role)

Environment variables:
  OPENWEBUI_URL              URL of Open WebUI (default: http://open-webui:8080)
  OPENWEBUI_ADMIN_EMAIL      Admin account email (default: admin@portal.local)
  OPENWEBUI_ADMIN_PASSWORD   Admin account password — REQUIRED, generated by launch.sh
  OPENWEBUI_ADMIN_NAME       Admin display name (default: Portal Admin)
  DEFAULT_USER_ROLE          Role for new signups: pending|user|admin (default: pending)
  ENABLE_SIGNUP              Allow self-registration: true|false (default: true)
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

import httpx

OPENWEBUI_URL = os.environ.get("OPENWEBUI_URL", "http://open-webui:8080").rstrip("/")
ADMIN_EMAIL = os.environ.get("OPENWEBUI_ADMIN_EMAIL", "admin@portal.local")
ADMIN_PASSWORD = os.environ.get("OPENWEBUI_ADMIN_PASSWORD")
if not ADMIN_PASSWORD:
    raise ValueError("OPENWEBUI_ADMIN_PASSWORD must be set in environment")
ADMIN_NAME = os.environ.get("OPENWEBUI_ADMIN_NAME", "Portal Admin")

# User management settings
DEFAULT_USER_ROLE = os.environ.get("DEFAULT_USER_ROLE", "pending")
ENABLE_SIGNUP = os.environ.get("ENABLE_SIGNUP", "true").lower() == "true"

IMPORTS_DIR = Path("/imports/openwebui")
MCP_FILE = IMPORTS_DIR / "mcp-servers.json"
WORKSPACES_DIR = IMPORTS_DIR / "workspaces"
PERSONAS_DIR = Path("/personas")

MAX_WAIT_SECONDS = 120
POLL_INTERVAL = 5


# --- Utilities ---------------------------------------------------------------

def wait_for_openwebui(client: httpx.Client) -> bool:
    """Poll until Open WebUI health endpoint responds."""
    print(f"Waiting for Open WebUI at {OPENWEBUI_URL}...")
    deadline = time.time() + MAX_WAIT_SECONDS
    while time.time() < deadline:
        try:
            resp = client.get(f"{OPENWEBUI_URL}/health", timeout=5.0)
            if resp.status_code == 200:
                print("  Open WebUI is healthy")
                return True
        except Exception:
            pass
        print(f"  Not ready yet - retrying in {POLL_INTERVAL}s...")
        time.sleep(POLL_INTERVAL)
    print("ERROR: Open WebUI did not become ready in time")
    return False


def create_admin_account(client: httpx.Client) -> str | None:
    """Create the admin account. Returns API token or None if already exists."""
    print(f"Creating admin account: {ADMIN_EMAIL}")
    try:
        resp = client.post(
            f"{OPENWEBUI_URL}/api/v1/auths/signup",
            json={
                "name": ADMIN_NAME,
                "email": ADMIN_EMAIL,
                "password": ADMIN_PASSWORD,
            },
            timeout=15.0,
        )
        if resp.status_code in (200, 201):
            token = resp.json().get("token")
            print("  Admin account created")
            return token
        elif resp.status_code == 400:
            # User already exists - this is expected on non-first runs
            detail = resp.json().get("detail", "")
            if "already" in detail.lower() or "exist" in detail.lower():
                print("  Admin account already exists (not first run)")
                return None
            print(f"  Signup failed: {detail}")
            return None
        else:
            print(f"  Signup failed: HTTP {resp.status_code} - {resp.text[:150]}")
            return None
    except Exception as e:
        print(f"  Signup error: {e}")
        return None


def login(client: httpx.Client) -> str | None:
    """Login and return API token."""
    print(f"Logging in as: {ADMIN_EMAIL}")
    try:
        resp = client.post(
            f"{OPENWEBUI_URL}/api/v1/auths/signin",
            json={"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD},
            timeout=15.0,
        )
        if resp.status_code == 200:
            token = resp.json().get("token")
            print("  Login successful")
            return token
        else:
            print(f"  Login failed: HTTP {resp.status_code} - {resp.text[:150]}")
            return None
    except Exception as e:
        print(f"  Login error: {e}")
        return None


def auth_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


# --- Tool Server Registration -------------------------------------------------

def register_tool_servers(client: httpx.Client, token: str) -> None:
    """Register all Portal MCP servers as Tool Servers in Open WebUI."""
    print("\nRegistering MCP Tool Servers...")

    if not MCP_FILE.exists():
        print(f"  Skipping - {MCP_FILE} not found")
        return

    servers = json.loads(MCP_FILE.read_text()).get("tool_servers", [])
    if not servers:
        print("  Skipping - no tool_servers in mcp-servers.json")
        return

    # Get existing registrations
    existing_urls: set[str] = set()
    try:
        resp = client.get(
            f"{OPENWEBUI_URL}/api/v1/tools/server/",
            headers=auth_headers(token),
        )
        if resp.status_code == 200:
            data = resp.json()
            for s in (data if isinstance(data, list) else data.get("data", [])):
                existing_urls.add(s.get("url", ""))
    except Exception as e:
        print(f"  Warning: could not check existing tool servers: {e}")

    registered = skipped = failed = 0
    for server in servers:
        url = server["url"]
        name = server["name"]
        key = server.get("api_key", "")

        if url in existing_urls:
            print(f"  Skip (exists): {name}")
            skipped += 1
            continue

        try:
            resp = client.post(
                f"{OPENWEBUI_URL}/api/v1/tools/server/",
                json={
                    "url": url,
                    "config": {
                        "name": name,
                        "auth_type": "none" if not key else "bearer",
                        "key": key,
                    },
                },
                headers=auth_headers(token),
                timeout=10.0,
            )
            if resp.status_code in (200, 201):
                print(f"  Registered: {name}")
                registered += 1
            else:
                print(f"  Failed {name}: HTTP {resp.status_code} - {resp.text[:100]}")
                failed += 1
        except Exception as e:
            print(f"  Error {name}: {e}")
            failed += 1

    print(f"  Done: {registered} registered, {skipped} skipped, {failed} failed")


# --- Workspace Creation -------------------------------------------------------

def create_workspaces(client: httpx.Client, token: str) -> None:
    """Create Portal workspace presets in Open WebUI."""
    print("\nCreating Workspaces...")

    if not WORKSPACES_DIR.exists():
        print(f"  Skipping - {WORKSPACES_DIR} not found")
        return

    ws_files = sorted(WORKSPACES_DIR.glob("workspace_*.json"))
    if not ws_files:
        print("  Skipping - no workspace files found")
        return

    # Get existing workspaces
    existing_names: set[str] = set()
    try:
        resp = client.get(
            f"{OPENWEBUI_URL}/api/v1/models/",
            headers=auth_headers(token),
        )
        if resp.status_code == 200:
            data = resp.json()
            models = data if isinstance(data, list) else data.get("data", [])
            for m in models:
                existing_names.add(m.get("id", ""))
    except Exception as e:
        print(f"  Warning: could not check existing models: {e}")

    created = skipped = failed = 0
    for ws_file in ws_files:
        ws = json.loads(ws_file.read_text())
        ws_id = ws.get("id", "")

        if ws_id in existing_names:
            print(f"  Skip (exists): {ws['name']}")
            skipped += 1
            continue

        payload = {
            "id": ws_id,
            "name": ws["name"],
            "meta": ws.get("meta", {}),
            "params": ws.get("params", {}),
        }

        try:
            resp = client.post(
                f"{OPENWEBUI_URL}/api/v1/models/",
                json=payload,
                headers=auth_headers(token),
                timeout=10.0,
            )
            if resp.status_code in (200, 201):
                print(f"  Created: {ws['name']}")
                created += 1
            else:
                print(f"  Failed {ws['name']}: HTTP {resp.status_code} - {resp.text[:100]}")
                failed += 1
        except Exception as e:
            print(f"  Error {ws['name']}: {e}")
            failed += 1

    print(f"  Done: {created} created, {skipped} skipped, {failed} failed")


# --- Persona Presets -----------------------------------------------------------

def create_persona_presets(client: httpx.Client, token: str, personas_dir: Path) -> None:
    """Create Open WebUI model presets from persona YAML files."""
    import yaml as _yaml

    print("\nCreating Persona Model Presets...")
    if not personas_dir.exists():
        print(f"  Skipping — {personas_dir} not found")
        return

    persona_files = sorted(personas_dir.glob("*.yaml"))
    if not persona_files:
        print("  Skipping — no persona YAML files found")
        return

    # Get existing models to avoid duplicates
    existing_ids: set[str] = set()
    try:
        resp = client.get(f"{OPENWEBUI_URL}/api/v1/models/", headers=auth_headers(token))
        if resp.status_code == 200:
            data = resp.json()
            for m in (data if isinstance(data, list) else data.get("data", [])):
                existing_ids.add(m.get("id", ""))
    except Exception as e:
        print(f"  Warning: could not fetch existing models: {e}")

    created = skipped = failed = 0
    for f in persona_files:
        try:
            persona = _yaml.safe_load(f.read_text())
        except Exception as e:
            print(f"  Skip {f.name}: parse error — {e}")
            continue

        slug = persona.get("slug", f.stem)
        name = persona.get("name", slug)
        system_prompt = persona.get("system_prompt", "")
        workspace_model = persona.get("workspace_model") or "dolphin-llama3:8b"

        if slug in existing_ids:
            print(f"  Skip (exists): {name}")
            skipped += 1
            continue

        payload = {
            "id": slug,
            "name": name,
            "meta": {
                "description": f"Portal persona: {name}",
                "profile_image_url": "",
                "tags": [{"name": persona.get("category", "general")}],
            },
            "params": {
                "system": system_prompt,
                "model": workspace_model,
            },
        }

        try:
            resp = client.post(
                f"{OPENWEBUI_URL}/api/v1/models/",
                json=payload,
                headers=auth_headers(token),
                timeout=10.0,
            )
            if resp.status_code in (200, 201):
                print(f"  Created persona: {name} → {workspace_model}")
                created += 1
            else:
                print(f"  Failed {name}: HTTP {resp.status_code}")
                failed += 1
        except Exception as e:
            print(f"  Error {name}: {e}")
            failed += 1

    print(f"  Done: {created} created, {skipped} skipped, {failed} failed")


def configure_user_settings(client: httpx.Client, token: str) -> None:
    """Configure Open WebUI user management settings post-bootstrap."""
    print("\nConfiguring user settings...")

    default_role = DEFAULT_USER_ROLE

    try:
        # Enable/disable signup
        resp = client.post(
            f"{OPENWEBUI_URL}/api/v1/auths/signup/enabled",
            json={"enable_signup": ENABLE_SIGNUP},
            headers=auth_headers(token),
            timeout=10.0,
        )
        if resp.status_code in (200, 201):
            print(f"  Signup enabled: {ENABLE_SIGNUP}")
        else:
            print(f"  Warning: could not set signup mode: HTTP {resp.status_code}")
    except Exception as e:
        print(f"  Warning: signup config failed: {e}")

    print(f"  Default user role: {default_role}")
    print(f"  Note: New users with role 'pending' must be approved by admin at:")
    print(f"        {OPENWEBUI_URL}/admin/users")


# --- Main ---------------------------------------------------------------------

def main() -> int:
    client = httpx.Client(timeout=30.0)

    # Wait for Open WebUI to be ready
    if not wait_for_openwebui(client):
        return 1

    # Create admin account (first run) or skip if exists
    token = create_admin_account(client)

    # If signup failed (account exists), login instead
    if token is None:
        token = login(client)

    if not token:
        print("ERROR: Could not obtain API token - check admin credentials in .env")
        print(f"  OPENWEBUI_ADMIN_EMAIL: {ADMIN_EMAIL}")
        print("  Set OPENWEBUI_ADMIN_EMAIL and OPENWEBUI_ADMIN_PASSWORD in .env")
        return 1

    # Seed the instance
    register_tool_servers(client, token)
    create_workspaces(client, token)
    configure_user_settings(client, token)
    create_persona_presets(client, token, PERSONAS_DIR)

    print("\nPortal Open WebUI initialization complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
