#!/usr/bin/env python3
"""
Open WebUI First-Run Initialization Script

Runs inside the openwebui-init Docker container after Open WebUI is healthy.
Handles:
  1. Admin account creation (first run only — idempotent on re-runs)
  2. MCP Tool Server registration via POST /api/v1/tools/server/
  3. Workspace model preset creation from imports/openwebui/workspaces/
  4. Persona model preset creation from config/personas/*.yaml
  5. User management settings (signup mode, default role)

Environment variables:
  OPENWEBUI_URL              URL of Open WebUI (default: http://open-webui:8080)
  OPENWEBUI_ADMIN_EMAIL      Admin account email (default: admin@portal.local)
  OPENWEBUI_ADMIN_PASSWORD   Admin account password — REQUIRED, generated by launch.sh
  OPENWEBUI_ADMIN_NAME       Admin display name (default: Portal Admin)
  DEFAULT_USER_ROLE          Role for new signups: pending|user|admin (default: pending)
  ENABLE_SIGNUP              Allow self-registration: true|false (default: true)
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import time
from pathlib import Path

import httpx

OPENWEBUI_URL = os.environ.get("OPENWEBUI_URL", "http://open-webui:8080").rstrip("/")
ADMIN_EMAIL = os.environ.get("OPENWEBUI_ADMIN_EMAIL", "admin@portal.local")
ADMIN_PASSWORD = os.environ.get("OPENWEBUI_ADMIN_PASSWORD")
if not ADMIN_PASSWORD:
    raise ValueError("OPENWEBUI_ADMIN_PASSWORD must be set in environment")
ADMIN_NAME = os.environ.get("OPENWEBUI_ADMIN_NAME", "Portal Admin")

# User management settings
DEFAULT_USER_ROLE = os.environ.get("DEFAULT_USER_ROLE", "pending")
ENABLE_SIGNUP = os.environ.get("ENABLE_SIGNUP", "true").lower() == "true"

IMPORTS_DIR = Path("/imports/openwebui")
MCP_FILE = IMPORTS_DIR / "mcp-servers.json"
WORKSPACES_DIR = IMPORTS_DIR / "workspaces"
PERSONAS_DIR = Path("/personas")

MAX_WAIT_SECONDS = 120
POLL_INTERVAL = 5


# --- Utilities ---------------------------------------------------------------


def wait_for_openwebui(client: httpx.Client) -> bool:
    """Poll until Open WebUI health endpoint responds."""
    print(f"Waiting for Open WebUI at {OPENWEBUI_URL}...")
    deadline = time.time() + MAX_WAIT_SECONDS
    while time.time() < deadline:
        try:
            resp = client.get(f"{OPENWEBUI_URL}/health", timeout=5.0)
            if resp.status_code == 200:
                print("  Open WebUI is healthy")
                return True
        except Exception:
            pass
        print(f"  Not ready yet - retrying in {POLL_INTERVAL}s...")
        time.sleep(POLL_INTERVAL)
    print("ERROR: Open WebUI did not become ready in time")
    return False


def create_admin_account(client: httpx.Client) -> str | None:
    """Create the admin account. Returns API token or None if already exists."""
    print(f"Creating admin account: {ADMIN_EMAIL}")
    try:
        resp = client.post(
            f"{OPENWEBUI_URL}/api/v1/auths/signup",
            json={
                "name": ADMIN_NAME,
                "email": ADMIN_EMAIL,
                "password": ADMIN_PASSWORD,
            },
            timeout=15.0,
        )
        if resp.status_code in (200, 201):
            token = resp.json().get("token")
            print("  Admin account created")
            return token
        elif resp.status_code == 400:
            # User already exists - this is expected on non-first runs
            detail = resp.json().get("detail", "")
            if "already" in detail.lower() or "exist" in detail.lower():
                print("  Admin account already exists (not first run)")
                return None
            print(f"  Signup failed: {detail}")
            return None
        else:
            print(f"  Signup failed: HTTP {resp.status_code} - {resp.text[:150]}")
            return None
    except Exception as e:
        print(f"  Signup error: {e}")
        return None


def login(client: httpx.Client) -> str | None:
    """Login and return API token."""
    print(f"Logging in as: {ADMIN_EMAIL}")
    try:
        resp = client.post(
            f"{OPENWEBUI_URL}/api/v1/auths/signin",
            json={"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD},
            timeout=15.0,
        )
        if resp.status_code == 200:
            token = resp.json().get("token")
            print("  Login successful")
            return token
        else:
            print(f"  Login failed: HTTP {resp.status_code} - {resp.text[:150]}")
            return None
    except Exception as e:
        print(f"  Login error: {e}")
        return None


def auth_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


# --- Tool Server Registration -------------------------------------------------


async def register_tool_servers_async(client: httpx.AsyncClient, token: str) -> None:
    """Register all Portal MCP servers as Tool Servers in Open WebUI.

    P5: uses /api/v1/configs/tool_servers endpoint (Open WebUI v0.6.5+).
    """
    print("\nRegistering MCP Tool Servers...")

    if not MCP_FILE.exists():
        print(f"  Skipping - {MCP_FILE} not found")
        return

    servers = json.loads(MCP_FILE.read_text()).get("tool_servers", [])
    if not servers:
        print("  Skipping - no tool_servers in mcp-servers.json")
        return

    # Build tool server connections in the format expected by Open WebUI
    connections = []
    for s in servers:
        connections.append({
            "url": s.get("url", ""),
            "path": "openapi.json",
            "auth_type": "none" if not s.get("api_key") else "bearer",
            "key": s.get("api_key", ""),
            "config": {"enable": True},
        })

    try:
        resp = await client.post(
            f"{OPENWEBUI_URL}/api/v1/configs/tool_servers",
            json={"TOOL_SERVER_CONNECTIONS": connections},
            headers=auth_headers(token),
            timeout=15.0,
        )
        if resp.status_code in (200, 201):
            data = resp.json()
            count = len(data.get("TOOL_SERVER_CONNECTIONS", []))
            print(f"  Registered: {count} tool server(s)")
        else:
            print(f"  Warning: could not register tool servers: HTTP {resp.status_code} - {resp.text[:200]}")
    except Exception as e:
        print(f"  Warning: tool server registration failed: {e}")


# --- Workspace Creation -------------------------------------------------------


async def create_workspaces_async(client: httpx.AsyncClient, token: str) -> None:
    """Create Portal workspace presets in Open WebUI."""
    print("\nCreating Workspaces...")

    # Ensure workspace toolIds are current before seeding
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location(
            "update_workspace_tools",
            Path(__file__).parent / "update_workspace_tools.py",
        )
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        if hasattr(mod, "main"):
            mod.main()
    except Exception as e:
        import logging

        logging.getLogger(__name__).warning("Could not update workspace toolIds: %s", e)

    if not WORKSPACES_DIR.exists():
        print(f"  Skipping - {WORKSPACES_DIR} not found")
        return

    ws_files = sorted(WORKSPACES_DIR.glob("workspace_*.json"))
    if not ws_files:
        print("  Skipping - no workspace files found")
        return

    # Get existing workspaces
    existing_names: set[str] = set()
    try:
        resp = await client.get(
            f"{OPENWEBUI_URL}/api/v1/models/",
            headers=auth_headers(token),
        )
        if resp.status_code == 200:
            data = resp.json()
            models = data if isinstance(data, list) else data.get("data", [])
            for m in models:
                existing_names.add(m.get("id", ""))
    except Exception as e:
        print(f"  Warning: could not check existing models: {e}")

    created = updated = failed = 0
    for ws_file in ws_files:
        ws = json.loads(ws_file.read_text())
        ws_id = ws.get("id", "")
        ws_name = ws.get("name", ws_id)
        ws_params = ws.get("params", {})
        ws_meta = ws.get("meta", {})

        # base_model_id is the actual model to route to (params.model may be "auto")
        base_model_id = ws_params.get("model", "dolphin-llama3:8b")
        if base_model_id == "auto":
            base_model_id = "dolphin-llama3:8b"

        payload = {
            "id": ws_id,
            "name": ws_name,
            "base_model_id": base_model_id,
            "meta": {
                "description": ws_meta.get("description", ws_name),
                "profile_image_url": ws_meta.get("profile_image_url", ""),
            },
            "params": ws_params,
        }

        try:
            if ws_id in existing_names:
                # Update existing workspace via correct endpoint
                resp = await client.post(
                    f"{OPENWEBUI_URL}/api/v1/models/model/update?id={ws_id}",
                    json=payload,
                    headers=auth_headers(token),
                    timeout=10.0,
                )
                if resp.status_code in (200, 201):
                    print(f"  Updated: {ws_name}")
                    updated += 1
                else:
                    print(f"  Skip (update failed {resp.status_code}): {ws_name}")
            else:
                resp = await client.post(
                    f"{OPENWEBUI_URL}/api/v1/models/create",
                    json=payload,
                    headers=auth_headers(token),
                    timeout=10.0,
                )
                if resp.status_code in (200, 201):
                    print(f"  Created: {ws_name}")
                    created += 1
                else:
                    print(f"  Failed {ws_name}: HTTP {resp.status_code}")
                    failed += 1
        except Exception as e:
            print(f"  Error {ws_name}: {e}")
            failed += 1

    print(f"  Workspaces: {created} created, {updated} updated, {failed} failed")


# --- Persona Presets -----------------------------------------------------------


async def create_persona_presets_async(
    client: httpx.AsyncClient, token: str, personas_dir: Path
) -> None:
    """Create Open WebUI model presets from persona YAML files.

    P5: parallelizes all POSTs via asyncio.gather — faster seeding.
    """
    import yaml as _yaml

    print("\nCreating Persona Model Presets...")
    if not personas_dir.exists():
        print(f"  Skipping — {personas_dir} not found")
        return

    persona_files = sorted(personas_dir.glob("*.yaml"))
    if not persona_files:
        print("  Skipping — no persona YAML files found")
        return

    # Get existing models to avoid duplicates
    existing_ids: set[str] = set()
    try:
        resp = await client.get(f"{OPENWEBUI_URL}/api/v1/models/", headers=auth_headers(token))
        if resp.status_code == 200:
            data = resp.json()
            for m in data if isinstance(data, list) else data.get("data", []):
                existing_ids.add(m.get("id", ""))
    except Exception as e:
        print(f"  Warning: could not fetch existing models: {e}")

    # Build persona payloads first (file reads, not network I/O)
    persona_payloads = []
    for f in persona_files:
        try:
            persona = _yaml.safe_load(f.read_text())
        except Exception as e:
            print(f"  Skip {f.name}: parse error — {e}")
            continue
        slug = persona.get("slug", f.stem)
        name = persona.get("name", slug)
        system_prompt = persona.get("system_prompt", "")
        workspace_model = persona.get("workspace_model") or "dolphin-llama3:8b"
        persona_payloads.append(
            (
                slug,
                name,
                workspace_model,
                {
                    "id": slug,
                    "name": name,
                    "base_model_id": workspace_model,
                    "meta": {
                        "description": f"Portal persona: {name}",
                        "profile_image_url": "",
                    },
                    "params": {
                        "system": system_prompt,
                        "model": workspace_model,
                    },
                },
            )
        )

    async def _post_one(
        slug: str, name: str, workspace_model: str, payload: dict
    ) -> tuple[str, str]:
        try:
            resp = await client.post(
                f"{OPENWEBUI_URL}/api/v1/models/create",
                json=payload,
                headers=auth_headers(token),
                timeout=10.0,
            )
            if resp.status_code in (200, 201):
                return (name, f"created:{workspace_model}")
            return (name, f"fail:{resp.status_code}")
        except Exception as e:
            return (name, f"error:{e}")

    # POST all personas in parallel (after filtering slugs already in existing_ids)
    to_create = [
        (slug, name, wm, payload)
        for slug, name, wm, payload in persona_payloads
        if slug not in existing_ids
    ]
    skipped = len(persona_payloads) - len(to_create)

    results = await asyncio.gather(
        *[_post_one(slug, name, wm, payload) for slug, name, wm, payload in to_create],
        return_exceptions=True,
    )

    created = failed = 0
    for result in results:
        if isinstance(result, Exception):
            failed += 1
            continue
        name, status = result
        if status.startswith("created:"):
            _, wm = status.split(":", 1)
            print(f"  Created persona: {name} → {wm}")
            created += 1
        else:
            print(f"  Failed {name}: {status}")
            failed += 1

    print(f"  Done: {created} created, {skipped} skipped, {failed} failed")


def configure_user_settings(client: httpx.Client, token: str) -> None:
    """Configure Open WebUI user management settings post-bootstrap."""
    print("\nConfiguring user settings...")
    print(f"  Default user role: {DEFAULT_USER_ROLE}")
    print("  Note: New users with role 'pending' must be approved by admin at:")
    print(f"        http://localhost:8080/admin/users")


def configure_audio_settings(client: httpx.Client, token: str) -> None:
    """Audio TTS/STT is configured via Open WebUI environment variables.

    AUDIO_TTS_ENGINE, AUDIO_TTS_OPENAI_API_BASE_URL, etc. are set in
    docker-compose.yml. No runtime API call needed.
    """
    print(
        "\nAudio settings: configured via environment variables (TTS→mcp-tts:8916, STT→mcp-whisper:8915)"
    )


def configure_tool_settings(client: httpx.Client, token: str) -> None:
    """Tool calling is enabled by default in Open WebUI.

    SAFE_MODE=false in docker-compose.yml env allows full tool access.
    No runtime API call needed — Open WebUI handles this natively.
    The /api/v1/configs/features endpoint does not exist in Open WebUI.
    """
    print("\nTool settings: enabled via SAFE_MODE=false in environment (no API call needed)")


# --- Main ---------------------------------------------------------------------


async def main() -> int:
    client = httpx.Client(timeout=30.0)

    # Wait for Open WebUI to be ready
    if not wait_for_openwebui(client):
        return 1

    # Create admin account (first run) or skip if exists
    token = create_admin_account(client)

    # If signup failed (account exists), login instead
    if token is None:
        token = login(client)

    if not token:
        print("ERROR: Could not obtain API token - check admin credentials in .env")
        print(f"  OPENWEBUI_ADMIN_EMAIL: {ADMIN_EMAIL}")
        print("  Set OPENWEBUI_ADMIN_EMAIL and OPENWEBUI_ADMIN_PASSWORD in .env")
        return 1

    # Seed the instance — P5: parallelize tool servers, workspaces, and persona presets
    # (configure_* are sync print-only helpers, no I/O, so no need to parallelize)
    async_client = httpx.AsyncClient(timeout=30.0)
    try:
        await asyncio.gather(
            register_tool_servers_async(async_client, token),
            create_workspaces_async(async_client, token),
            create_persona_presets_async(async_client, token, PERSONAS_DIR),
        )
    finally:
        await async_client.aclose()

    configure_user_settings(client, token)
    configure_audio_settings(client, token)
    configure_tool_settings(client, token)

    print("\nPortal Open WebUI initialization complete")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
