"""P0.4 (A5) — archive prose-only/orphaned RELEASE units via the real
`portal.platform.wiki.archive` bridge rule. No overrides."""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def _categorize(blocked: dict[str, list[str]]) -> dict[str, int]:
    """Tally blocked reasons by category for the phase report."""
    cat_counts: dict[str, int] = {}
    for reasons in blocked.values():
        for r in reasons:
            if "cites live source" in r:
                cat = "cites live source"
            elif "links" in r:
                cat = "live unit links it"
            elif "WIKI:GENERATED block" in r:
                cat = "doc block still references it"
            else:
                cat = "other"
            cat_counts[cat] = cat_counts.get(cat, 0) + 1
    return cat_counts


def main() -> None:
    sys.path.insert(0, str(REPO_ROOT))
    import portal.platform.wiki.store as store_mod
    from portal.platform.wiki.archive import archive_unit, check_archivable
    from scripts.spine_p0_manifest import classify

    result = classify(REPO_ROOT)
    candidates = sorted(set(result["archive"]) | set(result["release"]))

    # Cache one load_all() snapshot (avoids O(candidates*corpus) re-reads);
    # only makes a later archive more conservative, never unsafe.
    real_load_all = store_mod.load_all
    snapshot = real_load_all()
    store_mod.load_all = lambda: snapshot  # type: ignore[assignment]
    units = {u.id: u for u in snapshot}

    archived: list[str] = []
    blocked: dict[str, list[str]] = {}
    for uid in candidates:
        unit = units.get(uid)
        if unit is None:
            continue
        refusals = check_archivable(unit, REPO_ROOT)
        if refusals:
            blocked[uid] = refusals
            continue
        reason = (
            "P0.4 bridge-rule archive: prose-only unit with no executable claim, "
            "no volatile fact, and (post-A4 un-fencing) no live doc block or "
            "code/config source determining its truth"
        )
        ok, msg = archive_unit(uid, reason, REPO_ROOT)
        if ok:
            archived.append(uid)
        else:
            blocked[uid] = [msg]

    print(f"candidates: {len(candidates)}")
    print(f"archived:   {len(archived)}")
    print(f"blocked:    {len(blocked)}")

    cat_counts = _categorize(blocked)
    print("blocked reason categories:", cat_counts)

    out = REPO_ROOT / "docs" / "SPINE_P0_ARCHIVE_RUN.md"
    lines = [
        "<!-- GENERATED by scripts/spine_p0_archive_run.py — do not hand-edit -->",
        "",
        "# P0.4 Archive Run — Results",
        "",
        "No override, no `--superseded-by`, no weakened precondition: every",
        "candidate below either passed `archive.check_archivable`'s real bridge",
        "rule or is reported blocked with the exact refusal it raised. The",
        "dominant refusal (`cites live source`) is the bridge rule doing its",
        "job — the great majority of this corpus's RELEASE/ARCHIVE-classified",
        "prose genuinely cites a live code/config file, not just a generated",
        "doc, so archiving it would strand real grounding. Reducing this cohort",
        "further requires either a per-unit `--superseded-by` editorial pass",
        "(a survivor unit proven to cover every code path each archived unit",
        "cited — real editorial work, not mechanical) or an operator-approved",
        "redefinition of what counts as archivable prose; P0 does not take",
        "either unilaterally.",
        "",
        f"- Candidates (P0.1 ARCHIVE ∪ RELEASE, reclassified post-P0.3): **{len(candidates)}**",
        f"- Archived (bridge rule passed, no override): **{len(archived)}**",
        f"- Blocked (bridge rule refused): **{len(blocked)}**",
        "",
        "## Blocked reason categories",
        "",
    ]
    for cat, n in sorted(cat_counts.items(), key=lambda kv: -kv[1]):
        lines.append(f"- {cat}: {n}")
    lines += [
        "",
        "## Blocked units (first refusal reason)",
        "",
        "| unit id | reason |",
        "|---|---|",
    ]
    for uid, reasons in sorted(blocked.items()):
        lines.append(f"| `{uid}` | {reasons[0][:160]} |")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
