"""P0.1 — keep/release/archive manifest (read-only, TASK_BULLY_P0_SPINE_REDUCTION_V1).

KEEP-FACT: `claims` (A2) or `unit-fact-*` (A4). RELEASE: Tier-1-block prose,
not volatile. ARCHIVE: prose-only, unreferenced. Writes SPINE_P0_MANIFEST.md."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def classify(repo_root: Path | None = None) -> dict:
    """Full P0.1 classification: {keep_fact, release, archive: {id: reason}, total}."""
    import sys

    root = repo_root or REPO_ROOT
    sys.path.insert(0, str(root))
    from portal.platform.wiki.render import _MARKER_RE, TIER1_DOCS
    from portal.platform.wiki.store import load_all

    units = {u.id: u for u in load_all()}

    referenced: set[str] = set()
    for rel in TIER1_DOCS:
        p = root / rel
        if p.exists():
            referenced.update(_MARKER_RE.findall(p.read_text(encoding="utf-8")))

    keep_fact: dict[str, str] = {}
    release: dict[str, str] = {}
    archive: dict[str, str] = {}

    for uid, u in sorted(units.items()):
        if u.claims:
            keep_fact[uid] = "carries executable claims (A2 anti-drift core)"
        elif uid.startswith("unit-fact-"):
            keep_fact[uid] = "live-config-derived volatile-fact unit (A4)"
        elif uid in referenced:
            release[uid] = "prose feeding a Tier-1 WIKI:GENERATED block; not a volatile fact"
        else:
            archive[uid] = "prose-only: no claim, no fact, not referenced by a live doc block"

    return {
        "keep_fact": keep_fact,
        "release": release,
        "archive": archive,
        "total": len(units),
    }


def render_manifest(result: dict) -> str:
    lines = [
        "<!-- GENERATED by scripts/spine_p0_manifest.py — do not hand-edit -->",
        "",
        "# P0 Spine Reduction — Keep / Release / Archive Manifest",
        "",
        "Decision artifact for TASK_BULLY_P0_SPINE_REDUCTION_V1.md P0.1. `[GATE]`:",
        "produced read-only, best-evidenced classification made without a live",
        "operator sign-off in this run — flagged for review before P0.2+ acted on it.",
        "",
        f"- Total canonical units at generation time: **{result['total']}**",
        f"- KEEP-FACT: **{len(result['keep_fact'])}**",
        f"- RELEASE: **{len(result['release'])}**",
        f"- ARCHIVE: **{len(result['archive'])}**",
        "",
        "## KEEP-FACT",
        "",
        "Executable-claims anti-drift core (A2) plus live-config-derived volatile",
        "facts (A4). These keep a `WIKI:GENERATED` fence and stay AW-governed.",
        "",
        "| unit id | reason |",
        "|---|---|",
    ]
    for uid, reason in result["keep_fact"].items():
        lines.append(f"| `{uid}` | {reason} |")
    lines += [
        "",
        "## RELEASE",
        "",
        "Prose feeding a Tier-1 generated block with no live-probe claim and no",
        "volatile fact. P0.3 collapses these blocks to plain prose and drops the",
        "binding unit from the AW-governed set; P0.4 archives the now-orphaned unit.",
        "",
        "| unit id | reason |",
        "|---|---|",
    ]
    for uid, reason in result["release"].items():
        lines.append(f"| `{uid}` | {reason} |")
    lines += [
        "",
        "## ARCHIVE",
        "",
        "Prose-only units already unreferenced by any live generated block.",
        "P0.4 candidates for the archive bridge rule.",
        "",
        "| unit id | reason |",
        "|---|---|",
    ]
    for uid, reason in result["archive"].items():
        lines.append(f"| `{uid}` | {reason} |")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    result = classify()
    out = REPO_ROOT / "docs" / "SPINE_P0_MANIFEST.md"
    out.write_text(render_manifest(result), encoding="utf-8")
    print(
        f"wrote {out} ({result['total']} units: "
        f"{len(result['keep_fact'])} keep-fact / {len(result['release'])} release / "
        f"{len(result['archive'])} archive)"
    )
