#!/usr/bin/env bash
# GENERATED by bully_review_prune_ledger.py -- review, run one batch at a time,
# verify, commit. Nothing here has been executed.
set -euo pipefail

# batch 1: scripts that only exercise deletable modules
# (none)
uv run pytest tests -q -x && uv run python scripts/validate_system.py && git commit -m 'chore(bully): remove run scripts for retired modules'

# batch 2: tests that only exercise deletable modules
git rm -q tests/security/bully/test_p6_5_roster.py
uv run pytest tests -q -x && uv run python scripts/validate_system.py && git commit -m 'test(bully): remove tests for retired modules'

# batch 3: the modules themselves
git rm -q portal/modules/security/core/bully/roster.py
uv run pytest tests -q -x && uv run python scripts/validate_system.py && git commit -m 'refactor(bully): remove modules unreachable from the reviewer'
